library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use std.textio.all;

library vunit_lib;
context vunit_lib.vunit_context;
use vunit_lib.queue_pkg.all;

library osvvm;
use osvvm.RandomPkg.all;

library axi_stream;
use axi_stream.axi_stream_pkg.all;

library cnn_accel;
use cnn_accel.cnn_accel_pkg.all;
use cnn_accel.cnn_accel_isa_pkg.all;

-- Cross-language, bit-exact, end-to-end guard for cnn_accel_conv_core
-- ("M6b", see cnn_accel_conv_core.vhd's own header comment): drives the
-- REAL composed DUT (cnn_accel_window_gen -> cnn_accel_pe_array ->
-- cnn_accel_bias_requant, weight_buffer feeding pe_array) with the same
-- checked-in vector cases (modules/cnn_accel/test/vectors/, generated by
-- generate_vectors.py from cnn_accel_model.py) that every other RTL-facing
-- consumer of that golden model uses, and compares its 'm_out' stream
-- against 'expected.txt' byte-for-byte -- no VHDL re-derivation of the
-- conv math anywhere in this file (unlike tb_cnn_accel_pe_array.vhd's own
-- independent 'golden_beat_partial'). This is deliberately the same
-- cross-language contract tb_cnn_accel_pe_array_from_vectors.vhd already
-- guards for cnn_accel_pe_array alone, but through the whole composed
-- datapath (activations in, requantized int8 activations out), so a defect
-- at any of the three internal handshake boundaries this composition adds
-- (window_gen->pe_array, pe_array->bias_requant, weight_buffer's read
-- ports) would show up here even if each submodule's own standalone
-- testbench stays green.
--
-- Scope (matches cnn_accel_conv_core.vhd's own excluded-scope list): only
-- 'CONV2D'/'FC' vector cases are run (the ones with a 'weights_packed.txt'
-- -- 'DWCONV2D'/'POOL_MAX'/'POOL_AVG' need cnn_accel_pool or a different
-- weight layout not implemented by pack_weights_for_hw, see that
-- function's own docstring), and only cases whose 'out_channels <=
-- g_pe_rows' (every checked-in CONV2D/FC case already satisfies this --
-- layer-level output-channel tiling, re-streaming the whole ifmap once per
-- output-channel tile, is a future milestone cnn_accel_conv_core.vhd does
-- not implement, so this testbench cannot exercise more than one
-- output-channel tile either).
--
-- Weight/bias preload: this testbench IS the "future cnn_accel_axi_read_
-- dma instance" cnn_accel_conv_core.vhd's own header comment anticipates
-- for driving 'fill_start'/'fill_is_bias'/'s_weight' -- 'weights_
-- packed.txt' is streamed one int8 lane per fill beat (cnn_accel_weight_
-- buffer.vhd's own contract: one lane per accepted beat, auto-advancing),
-- in the exact flat order cnn_accel_model.pack_weights_for_hw already
-- wrote it (that function's docstring: this is precisely the order
-- 'weight_rd_addr' walks), so no reordering happens on this side either.
-- 'bias.txt' (LOGICAL, unpadded, 'out_channels' int32 values -- see test/
-- vectors/README.md) is zero-padded up to 'g_pe_rows' lanes here before
-- streaming (D11 -- no packed-bias vector file exists for these cases, so
-- this is the one place this testbench does its own trivial,
-- shape-only, zero-padding, not conv math).
--
-- Fill sessions: every case pulses 'fill_start' once before streaming its
-- own weight/bias set (see run_case), which is what makes
-- cnn_accel_weight_buffer's "new fill session" (write pointers reset to
-- 0) actually fire between cases -- single-buffered now, so there is no
-- bank to alternate any more; each case's fill fully overwrites the
-- previous case's weight/bias set before that case's own 'start' pulse.
entity tb_cnn_accel_conv_core is
  generic (
    -- Independent per-link randomized-backpressure generics, swept per
    -- test in module_cnn_accel.py's setup_vunit (0/0 for the dedicated
    -- full-throughput test, nonzero otherwise) -- mirrors every other
    -- cnn_accel testbench's identical in/out generic pair. 's_stream' is
    -- the one input link stalled; 'm_out' the one output link.
    stall_probability_percent_in : natural := 20;
    stall_probability_percent_out : natural := 20;
    -- Absolute path to modules/cnn_accel/test/vectors (self.path-derived
    -- in module_cnn_accel.py, so correct regardless of the simulator's
    -- own working directory) -- each case run below is a subdirectory of
    -- this.
    vectors_root : string;
    runner_cfg : string
  );
end entity tb_cnn_accel_conv_core;

architecture tb of tb_cnn_accel_conv_core is

  ------------------------------------------------------------------------
  -- DUT generics -- the reference hardware configuration point
  -- (doc/cnn_accel_tiled_dataflow_proposal.md section 7 / module_cnn_
  -- accel.py's own '_PE_ROWS'/'_PE_COLS'/'_TILE_CHANNELS'), fixed for
  -- this whole testbench (only runtime 'cfg_*' values vary between
  -- cases, exactly like a real compiled program would). 'c_max_row_tile_
  -- words'/'c_weight_buffer_depth' are sized generously for the small
  -- vector-case shapes actually exercised here (not the full '_MAX_ROW_
  -- TILE_WORDS'/'_WEIGHT_BUFFER_DEPTH' netlist-build values), for fast
  -- simulation.
  ------------------------------------------------------------------------

  constant c_pe_rows : positive := 8;
  constant c_pe_cols : positive := 8;
  constant c_tile_channels : positive := 8;
  constant c_max_kernel_size : positive := 3;
  constant c_accum_width : positive := 32;
  constant c_max_row_tile_words : positive := 64;
  constant c_weight_buffer_depth : positive := 64;
  -- Independent of 'c_weight_buffer_depth' -- every checked-in case has
  -- 'out_channels <= g_pe_rows' (run_case's own assert), so only bias row
  -- 0 is ever read; a handful of rows is generous headroom.
  constant c_bias_buffer_depth : positive := 4;

  constant c_weight_lanes : positive := c_pe_rows * c_pe_cols;

  constant c_opcode_conv2d : natural := to_integer(unsigned(OPCODE_CONV2D));
  constant c_opcode_fc : natural := to_integer(unsigned(OPCODE_FC));

  constant c_clk_period : time := 10 ns;

  signal clk : std_ulogic := '0';
  signal reset : std_ulogic := '1';

  signal cfg_kernel_h : std_ulogic_vector(7 downto 0) := (others => '0');
  signal cfg_kernel_w : std_ulogic_vector(7 downto 0) := (others => '0');
  signal cfg_stride_h : std_ulogic_vector(7 downto 0) := (others => '0');
  signal cfg_stride_w : std_ulogic_vector(7 downto 0) := (others => '0');
  signal cfg_pad_top : std_ulogic_vector(7 downto 0) := (others => '0');
  signal cfg_pad_bottom : std_ulogic_vector(7 downto 0) := (others => '0');
  signal cfg_pad_left : std_ulogic_vector(7 downto 0) := (others => '0');
  signal cfg_pad_right : std_ulogic_vector(7 downto 0) := (others => '0');
  signal cfg_in_width : std_ulogic_vector(15 downto 0) := (others => '0');
  signal cfg_in_height : std_ulogic_vector(15 downto 0) := (others => '0');
  signal cfg_in_channels : std_ulogic_vector(15 downto 0) := (others => '0');

  signal cfg_bias_en : std_ulogic := '0';
  signal cfg_requant_en : std_ulogic := '0';
  signal cfg_relu_en : std_ulogic := '0';
  signal cfg_requant_scale : std_ulogic_vector(31 downto 0) := (others => '0');
  signal cfg_requant_shift : std_ulogic_vector(7 downto 0) := (others => '0');

  signal start : std_ulogic := '0';
  signal done : std_ulogic;

  signal s_stream_m2s : axi_stream_m2s_t := axi_stream_m2s_init;
  signal s_stream_s2m : axi_stream_s2m_t;

  signal fill_start : std_ulogic := '0';
  signal fill_is_bias : std_ulogic := '0';
  signal s_weight_m2s : axi_stream_m2s_t := axi_stream_m2s_init;
  signal s_weight_s2m : axi_stream_s2m_t;

  signal m_out_m2s : axi_stream_m2s_t;
  signal m_out_s2m : axi_stream_s2m_t := (ready => '0');

  -- Non-blocking scoreboard for the single 'm_out' output link: one
  -- (packed data, last) pair pushed per expected pixel, popped and
  -- checked by 'monitor_out' on every accepted 'm_out' beat -- mirrors
  -- tb_cnn_accel_pe_array.vhd's identical 'expected_q' idiom.
  constant expected_q : queue_t := new_queue;

  -- One flat integer per vector-file line -- generate_vectors.py's own
  -- '_write_int_lines' format (test/vectors/README.md), narrowed on
  -- assignment into int8/int32 subtypes by the reader's caller.
  type flat_int_arr_t is array (natural range <>) of integer;

  function to_sl(cond : boolean) return std_ulogic is
  begin
    if cond then
      return '1';
    end if;
    return '0';
  end function;

  ------------------------------------------------------------------------
  -- Vector-file reader: one signed decimal integer per line, no header --
  -- same idiom as tb_cnn_accel_pe_array_from_vectors.vhd's identical
  -- helper.
  ------------------------------------------------------------------------

  procedure read_int_file(file_name : string; data : out flat_int_arr_t) is
    file f : text;
    variable l : line;
    variable v : integer;
    variable status : file_open_status;
  begin
    file_open(status, f, file_name, read_mode);
    assert status = open_ok
      report "tb_cnn_accel_conv_core: could not open '" & file_name & "'"
      severity failure;
    for i in data'range loop
      assert not endfile(f)
        report "tb_cnn_accel_conv_core: unexpected EOF in '" & file_name & "'"
        severity failure;
      readline(f, l);
      read(l, v);
      data(i) := v;
    end loop;
    file_close(f);
  end procedure;

  ------------------------------------------------------------------------
  -- 'desc.txt' field reader: one '<field> <value>' pair per line
  -- (test/vectors/README.md), lowercase keys matching 'LayerDesc'
  -- dataclass field names exactly. Looked up by name (not positionally)
  -- so field reordering in a future generate_vectors.py change cannot
  -- silently misread a value -- scans the whole file per call, which is
  -- fine for a ~26-line file called a dozen times per case.
  ------------------------------------------------------------------------

  impure function get_desc_field(case_dir : string; field_name : string) return integer is
    file f : text;
    variable l : line;
    variable status : file_open_status;
    variable key_buf : string(1 to field_name'length);
    variable value : integer;
    variable found : boolean := false;
  begin
    file_open(status, f, case_dir & "/desc.txt", read_mode);
    assert status = open_ok
      report "tb_cnn_accel_conv_core: could not open '" & case_dir & "/desc.txt'"
      severity failure;
    while not endfile(f) loop
      readline(f, l);
      if l'length >= field_name'length then
        read(l, key_buf);
        if key_buf = field_name then
          read(l, value);
          found := true;
        end if;
      end if;
    end loop;
    file_close(f);
    assert found
      report "tb_cnn_accel_conv_core: field '" & field_name & "' not found in '" &
        case_dir & "/desc.txt'"
      severity failure;
    return value;
  end function;

begin

  clk <= not clk after c_clk_period / 2;

  ------------------------------------------------------------------------
  dut : entity cnn_accel.cnn_accel_conv_core
    generic map (
      g_pe_rows => c_pe_rows,
      g_pe_cols => c_pe_cols,
      g_accum_width => c_accum_width,
      g_max_kernel_size => c_max_kernel_size,
      g_tile_channels => c_tile_channels,
      g_max_row_tile_words => c_max_row_tile_words,
      g_weight_buffer_depth => c_weight_buffer_depth,
      g_bias_buffer_depth => c_bias_buffer_depth
    )
    port map (
      clk => clk,
      reset => reset,

      cfg_kernel_h => cfg_kernel_h,
      cfg_kernel_w => cfg_kernel_w,
      cfg_stride_h => cfg_stride_h,
      cfg_stride_w => cfg_stride_w,
      cfg_pad_top => cfg_pad_top,
      cfg_pad_bottom => cfg_pad_bottom,
      cfg_pad_left => cfg_pad_left,
      cfg_pad_right => cfg_pad_right,
      cfg_in_width => cfg_in_width,
      cfg_in_height => cfg_in_height,
      cfg_in_channels => cfg_in_channels,

      cfg_bias_en => cfg_bias_en,
      cfg_requant_en => cfg_requant_en,
      cfg_relu_en => cfg_relu_en,
      cfg_requant_scale => cfg_requant_scale,
      cfg_requant_shift => cfg_requant_shift,

      start => start,
      done => done,

      s_stream_m2s => s_stream_m2s,
      s_stream_s2m => s_stream_s2m,

      fill_start => fill_start,
      fill_is_bias => fill_is_bias,
      s_weight_m2s => s_weight_m2s,
      s_weight_s2m => s_weight_s2m,

      m_out_m2s => m_out_m2s,
      m_out_s2m => m_out_s2m
    );

  ------------------------------------------------------------------------
  -- Output monitor: independent randomized-'ready' responder. Pops and
  -- checks the scoreboard queue on every accepted 'm_out' beat -- mirrors
  -- tb_cnn_accel_pe_array.vhd's identical 'monitor_out' process.
  ------------------------------------------------------------------------

  monitor_out : process
    variable rnd : RandomPType;
    variable expected_bytes : std_ulogic_vector(8 * c_pe_rows - 1 downto 0);
    variable expected_last : std_ulogic;
  begin
    rnd.InitSeed(get_string_seed(runner_cfg) & "_monitor");
    m_out_s2m.ready <= '0';
    wait until reset = '0' and rising_edge(clk);

    loop
      if rnd.RandInt(0, 99) < stall_probability_percent_out then
        m_out_s2m.ready <= '0';
        for i in 1 to rnd.RandInt(1, 4) loop
          wait until rising_edge(clk);
        end loop;
      end if;

      m_out_s2m.ready <= '1';
      wait until rising_edge(clk);

      if m_out_m2s.valid = '1' and m_out_s2m.ready = '1' then
        expected_bytes := pop(expected_q);
        expected_last := pop(expected_q);
        check_equal(
          m_out_m2s.data(8 * c_pe_rows - 1 downto 0), expected_bytes,
          "m_out data mismatch (Python golden model vs. real composed RTL)"
        );
        check_equal(m_out_m2s.last, expected_last, "m_out last mismatch");
      end if;
    end loop;
  end process;

  ------------------------------------------------------------------------
  main : process
    variable rnd : RandomPType;

    procedure do_reset is
    begin
      reset <= '1';
      wait until rising_edge(clk);
      reset <= '0';
    end procedure;

    -- Waits (bounded) until 'expected_q' has drained, then confirms it is
    -- truly empty (every expected output pixel actually arrived) --
    -- mirrors tb_cnn_accel_pe_array.vhd's identical 'drain_and_check'.
    procedure drain_and_check(max_wait_cycles : positive) is
      variable cycles : natural := 0;
    begin
      while not is_empty(expected_q) and cycles < max_wait_cycles loop
        wait until rising_edge(clk);
        cycles := cycles + 1;
      end loop;
      check_true(is_empty(expected_q), "m_out scoreboard queue did not drain in time");
    end procedure;

    -- Runs one checked-in vector case end to end: preload weight_buffer
    -- (weights then bias) after a fresh 'fill_start' pulse, configure and
    -- start the DUT, push every pixel's expected output, stream every
    -- input beat with randomized backpressure, then drain and check. See
    -- this file's own header comment for the full rationale of each step.
    procedure run_case(case_dir : string) is
      variable opcode : integer := get_desc_field(case_dir, "opcode");
      variable flags : integer := get_desc_field(case_dir, "flags");
      variable v_in_width : integer := get_desc_field(case_dir, "in_width");
      variable v_in_height : integer := get_desc_field(case_dir, "in_height");
      variable v_in_channels : integer := get_desc_field(case_dir, "in_channels");
      variable v_out_channels : integer := get_desc_field(case_dir, "out_channels");
      variable v_kernel_h : integer := get_desc_field(case_dir, "kernel_h");
      variable v_kernel_w : integer := get_desc_field(case_dir, "kernel_w");
      variable v_stride_h : integer := get_desc_field(case_dir, "stride_h");
      variable v_stride_w : integer := get_desc_field(case_dir, "stride_w");
      variable v_pad_top : integer := get_desc_field(case_dir, "pad_top");
      variable v_pad_bottom : integer := get_desc_field(case_dir, "pad_bottom");
      variable v_pad_left : integer := get_desc_field(case_dir, "pad_left");
      variable v_pad_right : integer := get_desc_field(case_dir, "pad_right");
      variable v_requant_scale : integer := get_desc_field(case_dir, "requant_scale");
      variable v_requant_shift : integer := get_desc_field(case_dir, "requant_shift");

      variable v_n_tiles : positive := (v_in_channels + c_tile_channels - 1) / c_tile_channels;
      variable v_out_width : positive :=
        (v_in_width + v_pad_left + v_pad_right - v_kernel_w) / v_stride_w + 1;
      variable v_out_height : positive :=
        (v_in_height + v_pad_top + v_pad_bottom - v_kernel_h) / v_stride_h + 1;
      variable v_num_pixels : positive := v_out_width * v_out_height;
      variable v_n_weight_vals : positive :=
        v_n_tiles * v_kernel_h * v_kernel_w * c_weight_lanes;

      variable weights_flat : flat_int_arr_t(0 to v_n_weight_vals - 1);
      variable bias_flat : flat_int_arr_t(0 to v_out_channels - 1);
      variable input_flat : flat_int_arr_t(0 to v_in_width * v_in_height * v_in_channels - 1);
      variable expected_flat : flat_int_arr_t(0 to v_num_pixels * v_out_channels - 1);

      variable tile_data : std_ulogic_vector(8 * c_tile_channels - 1 downto 0);
      variable expected_bytes : std_ulogic_vector(8 * c_pe_rows - 1 downto 0);
      variable ic : natural;
    begin
      assert opcode = c_opcode_conv2d or opcode = c_opcode_fc
        report "tb_cnn_accel_conv_core: run_case only supports CONV2D/FC vector cases " &
          "(pack_weights_for_hw's own ratified scope), got opcode=" & integer'image(opcode) &
          " from '" & case_dir & "'"
        severity failure;

      assert v_out_channels <= c_pe_rows
        report "tb_cnn_accel_conv_core: run_case only supports a single output-channel " &
          "tile (out_channels <= g_pe_rows) -- layer-level output-channel tiling is a " &
          "future milestone, see cnn_accel_conv_core.vhd's own entity-level comment; " &
          "got out_channels=" & integer'image(v_out_channels) & " from '" & case_dir & "'"
        severity failure;

      read_int_file(case_dir & "/weights_packed.txt", weights_flat);
      read_int_file(case_dir & "/bias.txt", bias_flat);
      read_int_file(case_dir & "/input.txt", input_flat);
      read_int_file(case_dir & "/expected.txt", expected_flat);

      -- Start a new fill session (write pointers reset to 0) before
      -- streaming any fill beat -- see this file's header comment. One
      -- idle cycle after the pulse keeps it unambiguous with respect to
      -- the first fill beat below (a beat presented the same cycle as
      -- 'fill_start' is not accepted).
      fill_start <= '1';
      wait until rising_edge(clk);
      fill_start <= '0';
      wait until rising_edge(clk);

      -- Fill weights: one int8 lane per beat, 'fill_is_bias'='0', in
      -- cnn_accel_model.pack_weights_for_hw's own flat order (that
      -- function's docstring: exactly the order 'weight_rd_addr' walks).
      fill_is_bias <= '0';
      for i in 0 to v_n_weight_vals - 1 loop
        s_weight_m2s.data(7 downto 0) <= std_ulogic_vector(to_signed(weights_flat(i), 8));
        s_weight_m2s.data(axi_stream_data_sz - 1 downto 8) <= (others => '0');
        s_weight_m2s.valid <= '1';
        wait until rising_edge(clk) and s_weight_s2m.ready = '1';
      end loop;
      s_weight_m2s.valid <= '0';

      -- Fill bias: one int32 lane per beat, 'fill_is_bias'='1', zero-
      -- padded up to 'c_pe_rows' lanes for output channels beyond
      -- 'v_out_channels' (D11 -- see this file's header comment; no
      -- packed-bias vector file exists for these cases).
      fill_is_bias <= '1';
      for i in 0 to c_pe_rows - 1 loop
        if i < v_out_channels then
          s_weight_m2s.data(31 downto 0) <= std_ulogic_vector(to_signed(bias_flat(i), 32));
        else
          s_weight_m2s.data(31 downto 0) <= (others => '0');
        end if;
        s_weight_m2s.data(axi_stream_data_sz - 1 downto 32) <= (others => '0');
        s_weight_m2s.valid <= '1';
        wait until rising_edge(clk) and s_weight_s2m.ready = '1';
      end loop;
      s_weight_m2s.valid <= '0';

      -- Configure and pulse 'start'.
      cfg_kernel_h <= std_ulogic_vector(to_unsigned(v_kernel_h, 8));
      cfg_kernel_w <= std_ulogic_vector(to_unsigned(v_kernel_w, 8));
      cfg_stride_h <= std_ulogic_vector(to_unsigned(v_stride_h, 8));
      cfg_stride_w <= std_ulogic_vector(to_unsigned(v_stride_w, 8));
      cfg_pad_top <= std_ulogic_vector(to_unsigned(v_pad_top, 8));
      cfg_pad_bottom <= std_ulogic_vector(to_unsigned(v_pad_bottom, 8));
      cfg_pad_left <= std_ulogic_vector(to_unsigned(v_pad_left, 8));
      cfg_pad_right <= std_ulogic_vector(to_unsigned(v_pad_right, 8));
      cfg_in_width <= std_ulogic_vector(to_unsigned(v_in_width, 16));
      cfg_in_height <= std_ulogic_vector(to_unsigned(v_in_height, 16));
      cfg_in_channels <= std_ulogic_vector(to_unsigned(v_in_channels, 16));
      cfg_bias_en <= to_sl((flags / 2) mod 2 = 1);
      cfg_requant_en <= to_sl((flags / 4) mod 2 = 1);
      cfg_relu_en <= to_sl(flags mod 2 = 1);
      cfg_requant_scale <= std_ulogic_vector(to_signed(v_requant_scale, 32));
      cfg_requant_shift <= std_ulogic_vector(to_unsigned(v_requant_shift, 8));

      wait until rising_edge(clk);
      start <= '1';
      wait until rising_edge(clk);
      start <= '0';

      -- Push every pixel's expected output up front (padded to
      -- 'c_pe_rows' bytes with 0 beyond 'v_out_channels' -- exact, not
      -- approximate, since a padded PE row's weight/bias are both 0, see
      -- this file's header comment).
      for p in 0 to v_num_pixels - 1 loop
        expected_bytes := (others => '0');
        for oc in 0 to v_out_channels - 1 loop
          expected_bytes(8 * (oc + 1) - 1 downto 8 * oc) :=
            std_ulogic_vector(to_signed(expected_flat(p * v_out_channels + oc), 8));
        end loop;
        push(expected_q, expected_bytes);
        push(expected_q, to_sl(p = v_num_pixels - 1));
      end loop;

      -- Feed 's_stream': raster order (row, col), 'v_n_tiles' beats per
      -- pixel, randomized input-side stall -- mirrors tb_cnn_accel_
      -- pe_array.vhd's/tb_cnn_accel_window_gen.vhd's identical
      -- 'send_*_beat' idiom.
      for row in 0 to v_in_height - 1 loop
        for col in 0 to v_in_width - 1 loop
          for tile in 0 to v_n_tiles - 1 loop
            tile_data := (others => '0');
            for c in 0 to c_tile_channels - 1 loop
              ic := tile * c_tile_channels + c;
              if ic < v_in_channels then
                tile_data(8 * (c + 1) - 1 downto 8 * c) :=
                  std_ulogic_vector(to_signed(
                    input_flat((row * v_in_width + col) * v_in_channels + ic), 8
                  ));
              end if;
            end loop;

            if rnd.RandInt(0, 99) < stall_probability_percent_in then
              s_stream_m2s.valid <= '0';
              for i in 1 to rnd.RandInt(1, 4) loop
                wait until rising_edge(clk);
              end loop;
            end if;

            s_stream_m2s.data(8 * c_tile_channels - 1 downto 0) <= tile_data;
            s_stream_m2s.data(axi_stream_data_sz - 1 downto 8 * c_tile_channels) <=
              (others => '0');
            s_stream_m2s.valid <= '1';
            wait until rising_edge(clk) and s_stream_s2m.ready = '1';
          end loop;
        end loop;
      end loop;
      s_stream_m2s.valid <= '0';

      drain_and_check(20000);
    end procedure;

    -- Runs every checked-in CONV2D/FC vector case (test/vectors/README.md's
    -- table), each with its own fresh 'fill_start' session -- see this
    -- file's header comment. Called identically by both tests below;
    -- only the stall generics (module_cnn_accel.py's per-test config)
    -- differ between them.
    procedure run_all_cases is
    begin
      run_case(vectors_root & "/conv1x1_c4_o4");
      run_case(vectors_root & "/conv3x3_s1_c3_o8_pad1");
      run_case(vectors_root & "/conv3x3_s2_c8_o8_pad1");
      run_case(vectors_root & "/conv3x3_s1_extremes");
      run_case(vectors_root & "/conv3x3_asymmetric_pad");
      run_case(vectors_root & "/conv3x3_negative_requant_scale");
      run_case(vectors_root & "/fc_in6_out4");
      run_case(vectors_root & "/conv3x3_c20_o6_multitile");
    end procedure;

  begin
    test_runner_setup(runner, runner_cfg);
    rnd.InitSeed(get_string_seed(runner_cfg));

    do_reset;
    wait until rising_edge(clk);

    if run("test_bitexact_backpressure") then
      -- Randomized independent per-link backpressure (generic-driven,
      -- nonzero by module_cnn_accel.py's per-test config) across every
      -- checked-in CONV2D/FC case, including the multi-tile case (T=3)
      -- that exercises the window_gen->pe_array first_tile/last_tile
      -- partial-sum-carry path end to end.
      run_all_cases;

    elsif run("test_bitexact_full_throughput") then
      -- Same cases, zero stall on both links (module_cnn_accel.py sets
      -- both stall generics to 0 for this test only) -- proves the
      -- composition sustains back-to-back beats with no artificially
      -- introduced bubble, on top of (not instead of) the correctness
      -- check every case already performs.
      run_all_cases;

    end if;

    test_runner_cleanup(runner);
  end process;

  test_runner_watchdog(runner, 5 ms);

end architecture tb;
