"""Frontend: MLIR generic-form parsing and printing for TOSA IR ingestion."""

from cnnc.frontend.mlir_generic import (
    Attr,
    BoolAttr,
    DenseArrayAttr,
    DenseElementsAttr,
    EnumAttr,
    FunctionType,
    FunctionTypeAttr,
    GenericFormRequired,
    IntAttr,
    MlirFunc,
    MlirModule,
    MlirOp,
    MlirParseError,
    ScalarType,
    StringAttr,
    TensorType,
    Type,
    TypeAttr,
    UndefinedValue,
    UnsupportedConstruct,
    UnsupportedLiteral,
    parse_file,
    parse_module,
    print_generic,
)
from cnnc.frontend.tosa_import import import_tosa, load_tosa_file

__all__ = [
    "Attr",
    "BoolAttr",
    "DenseArrayAttr",
    "DenseElementsAttr",
    "EnumAttr",
    "FunctionType",
    "FunctionTypeAttr",
    "GenericFormRequired",
    "IntAttr",
    "MlirFunc",
    "MlirModule",
    "MlirOp",
    "MlirParseError",
    "ScalarType",
    "StringAttr",
    "TensorType",
    "Type",
    "TypeAttr",
    "UndefinedValue",
    "UnsupportedConstruct",
    "UnsupportedLiteral",
    "import_tosa",
    "load_tosa_file",
    "parse_file",
    "parse_module",
    "print_generic",
]
