"""Frontend: MLIR generic-form parsing/printing and TOSA -> GIR import.

`supported_ops()` is the authoritative list of TOSA ops the importer
accepts; everything else is refused with a diagnostic that says whether
it is a host-side detection-head op or simply not implemented."""

from cnnc.frontend.mlir_generic import (
    Attr,
    BoolAttr,
    DenseArrayAttr,
    DenseElementsAttr,
    DenseResourceAttr,
    EnumAttr,
    FloatAttr,
    FunctionType,
    FunctionTypeAttr,
    GenericFormRequired,
    IntAttr,
    MlirFunc,
    MlirModule,
    MlirOp,
    MlirParseError,
    ResourceDecodeError,
    ScalarType,
    ShapeType,
    StringAttr,
    TensorType,
    Type,
    TypeAttr,
    UndefinedValue,
    UnsupportedConstruct,
    UnsupportedLiteral,
    parse_file,
    parse_resources,
    parse_module,
    print_generic,
)
from cnnc.frontend.tosa_import import import_tosa, load_tosa_file, supported_ops

__all__ = [
    "Attr",
    "BoolAttr",
    "DenseArrayAttr",
    "DenseElementsAttr",
    "DenseResourceAttr",
    "EnumAttr",
    "FloatAttr",
    "FunctionType",
    "FunctionTypeAttr",
    "GenericFormRequired",
    "IntAttr",
    "MlirFunc",
    "MlirModule",
    "MlirOp",
    "MlirParseError",
    "ResourceDecodeError",
    "ScalarType",
    "ShapeType",
    "StringAttr",
    "TensorType",
    "Type",
    "TypeAttr",
    "UndefinedValue",
    "UnsupportedConstruct",
    "UnsupportedLiteral",
    "import_tosa",
    "supported_ops",
    "load_tosa_file",
    "parse_file",
    "parse_resources",
    "parse_module",
    "print_generic",
]
