"""Hand-written network builder -- deliberately **not** TOSA/MLIR-based.

This is the object-oriented "model-building framework" a test author uses
to construct a small tensor program directly in Python: tensors carry a
shape and a quantization scale, and operations (`conv2d`, `add`,
`upsample2x`, `pool_max`/`pool_avg`, `copy`, `act`) are chained purely by
dataflow (an op's inputs are the `Tensor` objects returned by earlier
calls). `planner.py` turns the resulting graph into a residency-aware
program; `reference.py` executes it bit-exactly; `program.py` lowers it to
`DescV2`s and a `MemoryImage`.

Authoritative source for op semantics: `doc/cnn_accel_top_v2_arch.md`
section 5 (opcode table, W0 flags). The actual arithmetic is never
reimplemented here -- every numeric op is a thin wrapper that
`reference.py` later drives through `cnn_accel_model.py`'s existing
`conv2d`/`pool_max`/`pool_avg`/`bias_requantize_relu`. This module only
knows shapes, random data and which HW fields an op needs.

Weights/biases/inputs/per-channel scale tables are generated by a single
`random.Random(seed)` instance owned by the `Model`, consumed in
call order, so two `Model` runs built with the same seed (and the same
sequence of builder calls) produce byte-identical data -- the
determinism the spec's test list asks for.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum, auto
from itertools import count

import cnn_accel_model as golden

# ---------------------------------------------------------------------------
# Compiler-side helper: real scale -> (requant_scale, requant_shift).
#
# This has NO counterpart in cnn_accel_model.py: that module only knows how
# to *apply* a already-chosen (multiplier, shift) pair
# (`bias_requantize_relu`/`round_shift_right_signed`), which is the
# hardware-bit-exact half and is reused verbatim. Computing suitable
# fixed-point parameters from a floating-point ratio is a compiler
# concern with no hardware behaviour to be bit-exact against, so it is
# implemented here, once, rather than approximated ad hoc in every test.
# ---------------------------------------------------------------------------


def quantize_scale(real_scale: float, *, max_shift: int = 200) -> tuple[int, int]:
    """Choose a signed Q15 `requant_scale` (W9) and `requant_shift` (W10,
    `0..max_shift`) such that

        requant_scale / 2**(15 + requant_shift) ~= real_scale

    using as many mantissa bits as the 32-bit signed `requant_scale`
    field allows (`frexp`-normalize `real_scale` into `[0.5, 1)` times a
    power of two, then keep 32 bits of that mantissa), the same idea as
    TFLite's `QuantizeMultiplier` adapted to this ISA's Q15-plus-extra-
    shift encoding instead of a plain Q31 multiplier. Only used by
    `Model`'s builder methods to turn a friendly `output_scale`/
    `weight_scale` ratio into descriptor fields; never consulted by
    `reference.py`, which only ever *applies* the resulting
    `(requant_scale, requant_shift)` via `cnn_accel_model.
    bias_requantize_relu` (reused, not reimplemented)."""
    if real_scale <= 0:
        raise ValueError(f"real_scale must be positive, got {real_scale}")

    mantissa, exponent = math.frexp(real_scale)  # real_scale == mantissa * 2**exponent, 0.5 <= mantissa < 1
    shift = 16 - exponent
    if shift < 0:
        shift = 0
    if shift > max_shift:
        shift = max_shift

    multiplier = round(real_scale * (2 ** (15 + shift)))
    # Rounding at the mantissa's 0.5 boundary (or a large max_shift clamp)
    # can push the multiplier to/past 2**31; renormalize downward rather
    # than encode a value that would not round-trip through the signed
    # 32-bit `requant_scale` field.
    while multiplier >= 2**31 and shift > 0:
        multiplier = round(multiplier / 2)
        shift -= 1
    multiplier = min(multiplier, 2**31 - 1)
    return multiplier, shift


# ---------------------------------------------------------------------------
# Tensors and quantization.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class QuantParams:
    """Per-tensor symmetric int8 quantization: `real_value = int8_value *
    scale`. No zero-point: nowhere in the HW epilogue
    (`cnn_accel_model.bias_requantize_relu`) is a per-element zero-point
    subtracted -- the only additive term is the integer `output_offset`
    applied once, after the shift, to the whole lane. A caller targeting
    an asymmetric TOSA tensor must fold its zero-point into
    `output_offset` itself; `QuantParams` intentionally has no field that
    would suggest otherwise."""

    scale: float

    def __post_init__(self) -> None:
        if self.scale <= 0:
            raise ValueError(f"quant scale must be positive, got {self.scale}")


@dataclass(frozen=True)
class RowRange:
    """A half-open range of rows `[r0, r1)` in ONE tensor's own row
    coordinate system.

    Spatial tiling (`tiler.py`) is entirely a statement about row ranges:
    which rows of which full-resolution tensor a compact strip buffer
    holds, and which rows of an input a strip's output rows were computed
    from. Frozen (and therefore hashable) because a `RowRange` is a value,
    never a mutable cursor -- the tiler unions and translates them and
    must never alias one by accident."""

    r0: int  # inclusive
    r1: int  # exclusive

    def __post_init__(self) -> None:
        if self.r1 < self.r0:
            raise ValueError(f"RowRange: r1={self.r1} is below r0={self.r0}")

    @property
    def rows(self) -> int:
        return self.r1 - self.r0

    def clip(self, height: int) -> "RowRange":
        """This range intersected with `[0, height)` -- the receptive-field
        recurrence routinely produces a range that runs off the top or
        bottom of a tensor (that is exactly what padding is), and the
        strip buffer only ever holds rows that really exist."""
        return RowRange(max(0, self.r0), min(height, self.r1))

    def hull(self, other: "RowRange") -> "RowRange":
        """Smallest range containing both. Used to union the requirements
        of several consumers of one tensor: two consumers may ask for
        ranges that do not touch, and materializing the hull costs a few
        recomputed rows but keeps every strip buffer one contiguous,
        compact tensor (the only thing `in_plane_bytes` can describe --
        see `tiler.py`'s module docstring, hardware fact F2)."""
        return RowRange(min(self.r0, other.r0), max(self.r1, other.r1))

    def shift(self, delta: int) -> "RowRange":
        return RowRange(self.r0 + delta, self.r1 + delta)


@dataclass(frozen=True)
class StripOrigin:
    """Provenance of a strip tensor: which full-resolution tensor it is a
    piece of, and which of that tensor's rows this compact buffer holds.

    Never consulted by `planner.py`, `program.py` or `reference.py` -- it
    exists so the tiler's own geometry assertions, the tests and a
    program dump can say *what a buffer is* without re-deriving it from
    the addresses. The project's standing blind spot is that the DUT and
    `reference.py` both take their addresses from the planner, so a
    placement bug is self-consistently wrong on both sides; an
    independent record of the intended geometry is what a test checks the
    plan against."""

    full: "Tensor"
    rows: RowRange
    strip: int


@dataclass
class Tensor:
    """One node in the dataflow graph. `height/width/channels` is the
    LOGICAL HWC shape `cnn_accel_model.conv2d`/`pool_*` operate on --
    never the DDR channel-tiled-plane layout, which is a `reference.py`/
    `program.py` concern applied only at the memory boundary."""

    name: str
    height: int
    width: int
    channels: int
    quant: QuantParams
    producer: "Op | None" = None
    is_input: bool = False
    is_output: bool = False
    #: LOGICAL HWC int8 values, `-128..127`. Populated eagerly (from the
    #: model's RNG) for `is_input` tensors; populated for every other
    #: tensor only after `reference.run_reference` executes its producer.
    data: list[int] | None = None
    #: Indices into `Model.ops`, in the chronological order this tensor
    #: was consumed -- the liveness information `planner.py` needs and
    #: hardware deliberately does not track (section 3.1).
    consumers: list[int] = field(default_factory=list)

    # -- channel-plane aliasing (CONCAT / SPLIT, see `Model.concat`) -------
    #
    # The section-3 activation layout is channel-plane-major
    # (`byte_offset = ((c_tile * H + y) * W + x) * T + t`, `T = 8`), so a
    # tensor is exactly `ceil(C/T)` CONTIGUOUS planes of `H*W*T` bytes.
    # Concatenating along channels is therefore nothing but placing the
    # operands' planes back to back inside one buffer, and splitting
    # along a multiple-of-`T` channel boundary is nothing but naming a
    # sub-range of a parent's planes. Both are expressed here as an
    # *alias edge* to a parent tensor and cost no opcode, no instruction
    # and no byte of data movement.

    #: The tensor whose buffer this one lives inside, or `None` when this
    #: tensor owns its own allocation (it is an alias "root").
    alias_parent: "Tensor | None" = None
    #: This tensor's first plane, counted in `T`-channel planes from
    #: `alias_parent`'s first plane. Meaningless when `alias_parent` is
    #: `None`.
    alias_plane_offset: int = 0
    #: Which direction the alias edge carries data:
    #:
    #: * ``"part"``  -- this tensor's *producer writes into* the parent's
    #:   buffer; the parent (a CONCAT result) has no producer of its own
    #:   and its contents are the union of its parts.
    #: * ``"slice"`` -- this tensor is a read-only view *derived from* the
    #:   parent's contents (a SPLIT output, or a CONCAT that turned out to
    #:   be a contiguous re-view of one existing tensor).
    alias_role: str | None = None
    #: The tensors aliased into this one with `alias_role == "part"`, in
    #: ascending `alias_plane_offset` order. Non-empty exactly for a
    #: CONCAT result that owns a buffer.
    alias_parts: list["Tensor"] = field(default_factory=list)

    # -- spatial tiling (see `tiler.py`) ------------------------------------

    #: Set by `tiler.py` on a strip buffer: which rows of which
    #: full-resolution tensor these bytes are. `None` for every tensor of
    #: an untiled graph.
    origin: "StripOrigin | None" = None
    #: Keep this tensor in DDR for its whole lifetime, unconditionally.
    #:
    #: A full-resolution tensor on a fusion-group boundary is written by
    #: `S` separate strip `RowCopyOp`s and read by the next group's, so it
    #: has no single producer, several writers, and a lifetime spanning
    #: groups -- it is backing storage by design, not a scratchpad
    #: resident. `planner.py` takes its existing `place_in_ddr` path for
    #: such a tensor immediately and unconditionally, and reports the
    #: bytes separately (`DdrTraffic.pinned_*_bytes`) from the bytes an
    #: overflow *fallback* cost, so a test can still assert "this program
    #: paid nothing for overflow" while the group boundaries cost exactly
    #: what the tiling says they should.
    pin_ddr: bool = False
    #: The granularity at which this tensor's buffer must stay inside one
    #: `cnn_accel_tensor_mem` bank (see `planner._LocalAllocator`), or
    #: `None` for "the whole buffer" -- which is what every untiled
    #: tensor wants and what this planner has always enforced.
    #:
    #: The hardware requirement is not "a buffer lies in one bank" but
    #: "no single *request* straddles a bank": `cnn_accel_tensor_mem`
    #: serves each request from the bank its address decodes to and
    #: silently clamps the overrun. For a strip activation buffer every
    #: request is at most one channel plane (`cmd_proc.vhd`'s ifmap
    #: feeder fetches one `(row, tile)` strip per request, output passes
    #: write one plane), so confining *planes* rather than the whole
    #: buffer is what lets a multi-plane strip be larger than a bank at
    #: all. Left `None` everywhere outside `tiler.py`, so no existing
    #: placement moves.
    confine_unit_bytes: int | None = None

    @property
    def size_bytes(self) -> int:
        """DDR/LOCAL_TENSOR byte footprint of this tensor in the
        section-3 channel-tiled-plane layout (identical in both spaces)."""
        return golden.activation_bytes(self.width, self.height, self.channels)

    @property
    def plane_bytes(self) -> int:
        """Bytes in one `T`-channel activation plane of this tensor."""
        return PLANE_CHANNELS * self.width * self.height

    @property
    def plane_count(self) -> int:
        return golden.activation_plane_count(self.channels)

    @property
    def row_bytes(self) -> int:
        """Bytes in one row of ONE `T`-channel activation plane. The unit
        a `RowCopyOp` moves: `plane_bytes` is `height * row_bytes`, and
        row `y` of plane `p` starts at `p * plane_bytes + y * row_bytes`."""
        return PLANE_CHANNELS * self.width


PLANE_CHANNELS = golden.ACTIVATION_PLANE_CHANNELS


def alias_root(tensor: Tensor) -> Tensor:
    """The tensor that actually owns the buffer `tensor` lives in --
    `tensor` itself when it is not aliased. Alias edges always point
    "outward" to a larger buffer and can nest (a CONCAT of a CONCAT
    result), so this walks the chain to its end."""
    node = tensor
    seen = 0
    while node.alias_parent is not None:
        node = node.alias_parent
        seen += 1
        if seen > 64:  # pragma: no cover - would mean a builder bug
            raise ValueError(f"alias chain from '{tensor.name}' does not terminate")
    return node


def alias_plane_offset_total(tensor: Tensor) -> int:
    """`tensor`'s first plane, counted from `alias_root(tensor)`'s first
    plane."""
    total = 0
    node = tensor
    while node.alias_parent is not None:
        total += node.alias_plane_offset
        node = node.alias_parent
    return total


def alias_byte_offset(tensor: Tensor) -> int:
    """Byte offset of `tensor` inside `alias_root(tensor)`'s buffer.

    Every alias edge preserves `height`/`width` (both `concat` and
    `split` require it), so one plane is the same number of bytes
    everywhere along the chain."""
    return alias_plane_offset_total(tensor) * tensor.plane_bytes


class Activation(Enum):
    """Epilogue activation choice for a compute op, orthogonal to
    `clamp` (section 5.1: `CLAMP_EN` set means `clamp_min`/`clamp_max`
    are used and `RELU_EN` is ignored; `CLAMP_EN` clear falls back to the
    legacy `RELU_EN`-selected `[0 or -128, 127]` range -- see
    `cnn_accel_model.bias_requantize_relu`)."""

    NONE = auto()
    RELU = auto()


# ---------------------------------------------------------------------------
# Ops. Each carries everything `reference.py`/`program.py` need: shapes
# live on the `Tensor`s, so an `Op` only carries the extra per-instruction
# parameters (kernel/stride/pad, weights, requant, ...).
# ---------------------------------------------------------------------------


@dataclass
class Op:
    name: str
    inputs: list[Tensor]
    output: Tensor


@dataclass
class Conv2dOp(Op):
    """`OPCODE_CONV2D`. `weight` is LOGICAL OHWI (module docstring of
    `cnn_accel_model.py`); `bias` is one int32 per output channel or
    `None` (`BIAS_EN` clear)."""

    weight: list[int]
    bias: list[int] | None
    kernel: tuple[int, int]
    stride: tuple[int, int]
    padding: tuple[int, int, int, int]  # (top, bottom, left, right)
    activation: Activation
    clamp: tuple[int, int] | None
    requant_scale: int
    requant_shift: int
    output_offset: int = 0
    per_channel_scale: list[tuple[int, int]] | None = None
    #: ISA v2.1 `pad_value`: the int8 value a padded tap takes -- the
    #: input tensor's quantization zero-point, NOT 0. Declared here rather
    #: than next to `padding` only because every field between them lacks
    #: a default and a dataclass cannot put a defaulted field first.
    #: Padding a quantized tensor with 0 adds `sum(w) * (0 - zp)` to every
    #: border accumulator; with YOLOv8n's 3x3/pad-1 convolutions that is
    #: every border output of every layer. 0 keeps pre-v2.1 behaviour.
    pad_value: int = 0
    #: ISA v2.0 `WEIGHT_REUSE` (R6): when set, this op's weight/bias/
    #: scale buffers are already resident from `reused_weight_op` and
    #: must not be refetched -- `planner.py` charges it zero weight
    #: bytes, `program.py` points its weight/bias/scale addresses at
    #: `reused_weight_op`'s own allocation instead of making a new one.
    weight_reuse: bool = False
    reused_weight_op: "Conv2dOp | None" = None
    #: Serve this op's packed weight/bias/scale images out of the
    #: scratchpad (`space_wgt = LOCAL_TENSOR`) instead of DDR.
    #:
    #: The hardware refills the weight buffer once per output-channel
    #: pass either way (`cmd_proc.vhd`'s `st_wgt_req`, which is skipped
    #: only by `WEIGHT_REUSE` and by `LOCAL_WEIGHT`); what this flag
    #: changes is where those `n_ot` fetches come *from*. For a tiled
    #: group that is the difference between reading the group's weights
    #: from DDR once per strip and reading them once in total: with `S`
    #: strips the DDR weight traffic goes from `S * W_G` to `W_G`, which
    #: on YOLOv8n at 256 KiB is several megabytes a frame.
    #:
    #: `planner.py` gives the images a local home (all convolutions
    #: sharing one `weight` list share one image), emits the `LOAD` as a
    #: `ConstLoadStep`, and silently falls back to DDR for the whole
    #: image if it cannot be placed -- so the flag is a request, never a
    #: promise, and a plan that ignores it is still correct.
    #:
    #: This is NOT `weight_reuse`: that flag skips the refill outright
    #: and is only correct for `out_channels <= PE_ROWS` (R8). The two
    #: are independent, and the tiler sets only this one.
    weights_resident: bool = False

    def flags(self) -> int:
        """W0 `flags` byte (section 5.1) for this op's `CONV2D`
        descriptor. The single place this is computed -- `reference.py`
        and `program.py` both call this rather than each re-deriving the
        same bits from `activation`/`clamp`/`bias`/`padding`/
        `per_channel_scale`/`weight_reuse`, so the executor and the
        descriptor emitter cannot silently disagree about which
        epilogue stages are enabled."""
        f = 0
        if self.bias is not None:
            f |= 1 << golden.FLAG_BIAS_EN
        f |= 1 << golden.FLAG_REQUANT_EN
        if self.clamp is not None:
            f |= 1 << golden.FLAG_CLAMP_EN
        elif self.activation == Activation.RELU:
            f |= 1 << golden.FLAG_RELU_EN
        if self.per_channel_scale is not None:
            f |= 1 << golden.FLAG_PER_CHANNEL_EN
        if any(self.padding):
            f |= 1 << golden.FLAG_PAD_EN
        if self.weight_reuse:
            f |= 1 << golden.FLAG_WEIGHT_REUSE
        return f

    def weight_layer_desc(self) -> golden.LayerDesc:
        """A minimal `cnn_accel_model.LayerDesc` carrying only the fields
        `pack_weights_for_hw`/`packed_weight_count`/`pack_bias_for_hw`/
        `pack_scale_table_for_hw` actually read (`in_channels`,
        `out_channels`, `kernel_h`, `kernel_w`). The single place both
        `planner.py` (byte-count prediction) and `program.py` (actual
        packing) build this from, so the two can never drift apart."""
        x = self.inputs[0]
        return golden.LayerDesc(
            opcode=golden.OPCODE_CONV2D,
            in_channels=x.channels,
            out_channels=self.output.channels,
            kernel_h=self.kernel[0],
            kernel_w=self.kernel[1],
        )


@dataclass
class PoolOp(Op):
    """`OPCODE_POOL_MAX`/`OPCODE_POOL_AVG`.

    ISA v2.1: pooling now has padding, reusing `CONV2D`'s own
    `FLAG_PAD_EN` + `pad_top/bottom/left/right` fields, plus `pad_value`
    -- the int8 value padded taps take, which for a real quantized tensor
    is its zero-point and NOT 0 (see `cnn_accel_model._pool_windows`).
    YOLOv8n's SPPF block is the motivating shape: 5x5 max pool, stride 1,
    padding 2, on a tensor with zero_point = -128."""

    mode: str  # "max" | "avg"
    kernel: tuple[int, int]
    stride: tuple[int, int]
    padding: tuple[int, int, int, int] = (0, 0, 0, 0)  # (top, bottom, left, right)
    pad_value: int = 0
    activation: Activation = Activation.NONE
    clamp: tuple[int, int] | None = None
    requant_scale: int = 0
    requant_shift: int = 0
    output_offset: int = 0

    def flags(self) -> int:
        """W0 `flags` byte for this op's `POOL_MAX`/`POOL_AVG`
        descriptor -- see `Conv2dOp.flags` for why this is centralized
        here rather than re-derived by each caller. `POOL_AVG` always
        sets `REQUANT_EN` (division is implemented as the epilogue's
        requantize step, section 5.2); `POOL_MAX` never does (integer
        max has no scale to correct)."""
        f = 0
        if self.mode == "avg":
            f |= 1 << golden.FLAG_REQUANT_EN
        if self.clamp is not None:
            f |= 1 << golden.FLAG_CLAMP_EN
        elif self.activation == Activation.RELU:
            f |= 1 << golden.FLAG_RELU_EN
        if any(self.padding):
            f |= 1 << golden.FLAG_PAD_EN
        return f


@dataclass
class AddOp(Op):
    """`OPCODE_ADD`: `dst = sat_i8(requant(src0) + requant(src1))`
    (section 5.2), one shared `(requant_scale, requant_shift)` pair
    applied identically to both operands -- see `reference.py`'s
    docstring for why (the descriptor has only one such pair for `ADD`,
    section 5.1's ambiguity resolved there)."""

    requant_scale: int
    requant_shift: int


@dataclass
class UpsampleOp(Op):
    """`OPCODE_UPSAMPLE`: nearest-neighbour replicate, factor 2 only
    (section 12 limitation 5 -- the only mode YOLOv8n needs)."""

    factor: int = 2


@dataclass
class DepthToSpaceOp(Op):
    """`OPCODE_DEPTH_TO_SPACE` (ISA v2.2): sub-pixel convolution's
    pixel-shuffle step. Trades channels for spatial resolution --
    `in_channels = factor**2 * out_channels`, output frame `factor` times
    larger in both dimensions -- and is the only op in the elementwise
    family that is not channel-preserving.

    PLANE-MAJOR channel grouping (`cin = (dy*factor + dx)*out_channels + c`),
    not PyTorch `nn.PixelShuffle`'s channel-major interleave; see
    `cnn_accel_model.depth_to_space` for why, and for the compile-time
    permutation a PyTorch-ordered graph needs first.

    Only `factor = 2` is implemented in v1 hardware
    (`cnn_accel_cmd_proc.chk_dts_geom_q`), which additionally requires
    `out_channels` to be a whole number of activation-plane tiles -- the
    hardware moves whole `T`-byte channel tiles and has nothing that can
    gather byte lanes out of one. `Model.depth_to_space` enforces both up
    front rather than letting a malformed descriptor reach the DUT."""

    factor: int = 2


@dataclass
class CopyOp(Op):
    """`OPCODE_COPY`: opaque byte copy, `xfer_bytes` long. Never
    interprets its payload as activation elements (no pack/unpack at
    either end), which is why it is legal between any two spaces/
    addresses of matching length regardless of tensor shape."""


@dataclass
class ActOp(Op):
    """`OPCODE_ACT`: standalone 256-entry signed int8 -> int8 LUT."""

    lut: list[int]


@dataclass
class RowCopyOp(Op):
    """Move rows `src_rows` of `inputs[0]` into rows `dst_rows` of
    `output`, **plane by plane**.

    This is the one new operation spatial tiling needs, and it needs no
    new opcode: the planner lowers it to `plane_count` ordinary
    `LOAD`/`STORE`/`COPY` descriptors (one opcode family, chosen purely
    from the two resolved operand spaces, exactly as `MoveStep` already
    is), each moving `rows * width * T` bytes

        src + p*src.plane_bytes + src_rows.r0*src.row_bytes
     -> dst + p*dst.plane_bytes + dst_rows.r0*dst.row_bytes

    One descriptor per plane rather than one for the lot, because the
    activation layout is channel-plane-major: a row window of a
    multi-plane tensor is `plane_count` separate byte ranges, `plane_bytes`
    apart, and the two ends have *different* plane strides whenever the
    strip and the full tensor differ in height (which is the normal case
    -- see hardware fact F2 in `tiler.py`'s docstring). A single-plane
    tensor's row window is contiguous and the lowering degenerates to one
    descriptor.

    `output` is one of three things, and the planner does not need to
    know which:

    * a fresh compact tensor of `src_rows.rows` rows -- the *extract*
      form, used to align a join operand's rows with the join's, and to
      pull a strip out of a pinned group input;
    * a `concat` part -- then this op is that part's producer and writes
      straight into the concat slot, which is the existing
      "producer-directed placement" rule with a `RowCopyOp` as producer;
    * a pinned full-resolution tensor, written at a row offset -- the
      *store* form that assembles a group output from `S` strips.

    Widths and plane counts must match at the two ends (a row copy never
    reshapes channels and never splits a plane); heights need not.
    """

    src_rows: RowRange
    dst_rows: RowRange


# ---------------------------------------------------------------------------
# Model: the graph builder.
# ---------------------------------------------------------------------------


class Model:
    """A small, explicit dataflow graph plus the deterministic RNG that
    fills in every op's random weights/biases/inputs/per-channel scale
    tables. Two `Model(seed=S)` built by an identical sequence of calls
    are byte-identical; a different `seed` (almost certainly) is not --
    exercised directly by `tests/test_model.py`'s determinism test."""

    def __init__(self, seed: int, name: str = "model", *, shapes_only: bool = False) -> None:
        """`shapes_only` builds a graph for **planning only**: weights,
        biases, scale tables and input data are left empty instead of
        drawn from the RNG.

        It exists for one purpose: reasoning about a network at its real
        size. YOLOv8n's weights are 3.2 million int8 values, and the
        tiling selection rule (`tiling_select.py`) plans a few thousand
        candidate strip sub-programs over them -- drawing and copying
        those lists would dominate the run by orders of magnitude while
        changing nothing, since `planner.py` only ever asks a conv for
        its *shape* (`Conv2dOp.weight_layer_desc`, whose byte counts come
        from the channel and kernel counts alone). A `shapes_only` model
        must never be handed to `reference.py` or `program.py`, which do
        read the values."""
        self.seed = seed
        self.name = name
        self.shapes_only = shapes_only
        self._rng = _Rng(seed)
        self.ops: list[Op] = []
        self.tensors: list[Tensor] = []
        self.inputs: list[Tensor] = []
        self.outputs: list[Tensor] = []
        self._counter = count()

    # -- naming / bookkeeping ---------------------------------------------

    def _auto_name(self, prefix: str) -> str:
        return f"{prefix}{next(self._counter)}"

    def _register_op(self, op: Op) -> None:
        op_index = len(self.ops)
        for t in op.inputs:
            t.consumers.append(op_index)
        self.ops.append(op)
        self.tensors.append(op.output)

    # -- graph inputs/outputs ----------------------------------------------

    def input(
        self, height: int, width: int, channels: int, scale: float = 1.0, name: str | None = None
    ) -> Tensor:
        """A tensor materialized in DDR before the program starts (the
        residency policy's one legitimate "initial input" round trip).
        Its data is generated now, deterministically, from the model's
        RNG."""
        t = Tensor(
            name=name or self._auto_name("input"),
            height=height,
            width=width,
            channels=channels,
            quant=QuantParams(scale),
            is_input=True,
        )
        t.data = [] if self.shapes_only else self._rng.int8_list(height * width * channels)
        self.inputs.append(t)
        self.tensors.append(t)
        return t

    def output(self, tensor: Tensor) -> Tensor:
        """Mark `tensor` a graph output: `planner.py` always lands it in
        the DDR `OUTPUTS` region (never `LOCAL_TENSOR`), matching the
        residency policy's "DDR is backing storage only... for... final
        outputs"."""
        if tensor.is_output:
            return tensor
        if tensor.alias_parent is not None:
            raise ValueError(
                f"cannot mark '{tensor.name}' a graph output: it is aliased into "
                f"'{alias_root(tensor).name}''s buffer (as a "
                f"{tensor.alias_role} at plane offset {alias_plane_offset_total(tensor)}), "
                "and a graph output must own a DDR OUTPUTS allocation of its own. "
                f"Use `model.output(model.copy({tensor.name!r}-tensor))` to materialize "
                "an independent copy first."
            )
        tensor.is_output = True
        self.outputs.append(tensor)
        return tensor

    # -- ops -----------------------------------------------------------------

    def conv2d(
        self,
        x: Tensor,
        out_channels: int,
        *,
        kernel: tuple[int, int] = (3, 3),
        stride: tuple[int, int] = (1, 1),
        padding: tuple[int, int, int, int] = (0, 0, 0, 0),
        pad_value: int = 0,
        bias: bool = True,
        activation: Activation = Activation.RELU,
        clamp: tuple[int, int] | None = None,
        requant_scale: int | None = None,
        requant_shift: int | None = None,
        weight_scale: float = 1.0,
        output_scale: float = 1.0,
        per_channel: bool = False,
        weight_reuse_from: Tensor | None = None,
        name: str | None = None,
    ) -> Tensor:
        """`CONV2D`. `padding` is `(top, bottom, left, right)`.

        `pad_value` is the int8 value padded taps take (ISA v2.1) -- the
        input tensor's quantization zero-point in a real network, not 0.
        `QuantParams` models symmetric quantization and has no zero-point
        field, so it is passed explicitly, exactly as `pool_max`/
        `pool_avg` take it; the default of 0 keeps every existing program
        bit-identical.

        If `requant_scale`/`requant_shift` are both omitted they are
        derived from `x.quant.scale * weight_scale / output_scale` via
        `quantize_scale` -- convenient for a test that only cares about
        shapes, while boundary-rounding tests can still pass exact
        integers.

        `weight_reuse_from` names the OUTPUT tensor of an earlier
        `conv2d` call whose weight/bias/scale-table this op reuses
        verbatim (ISA v2.0 `WEIGHT_REUSE`, R6); geometry
        (`in_channels`/`out_channels`/`kernel`) must match, checked here
        rather than left for `program.py` to discover late."""
        kh, kw = kernel
        sh, sw = stride
        pt, pb, pl, pr = padding
        out_h = (x.height + pt + pb - kh) // sh + 1
        out_w = (x.width + pl + pr - kw) // sw + 1
        if out_h <= 0 or out_w <= 0:
            raise ValueError(f"conv2d: non-positive output dims out_h={out_h} out_w={out_w}")
        if not -128 <= pad_value <= 127:
            raise ValueError(f"conv2d: pad_value must be int8, got {pad_value}")

        if weight_reuse_from is not None:
            reused = weight_reuse_from.producer
            if not isinstance(reused, Conv2dOp):
                raise TypeError("weight_reuse_from must be the output of an earlier conv2d")
            if reused.inputs[0].channels != x.channels or reused.kernel != kernel:
                raise ValueError(
                    "weight_reuse_from geometry mismatch: reused conv has "
                    f"in_channels={reused.inputs[0].channels} kernel={reused.kernel}, "
                    f"this conv wants in_channels={x.channels} kernel={kernel}"
                )
            if reused.output.channels != out_channels:
                raise ValueError(
                    f"weight_reuse_from has out_channels={reused.output.channels}, "
                    f"this conv wants out_channels={out_channels}"
                )
            weight, bias_values, per_channel_scale = reused.weight, reused.bias, reused.per_channel_scale
        elif self.shapes_only:
            reused = None
            weight = []
            bias_values = [0] * out_channels if bias else None
            per_channel_scale = [(1, 0)] * out_channels if per_channel else None
        else:
            reused = None
            weight = self._rng.int8_list(out_channels * kh * kw * x.channels, low=-127, high=127)
            bias_values = self._rng.bias_list(out_channels) if bias else None
            per_channel_scale = self._rng.scale_table(out_channels) if per_channel else None

        if requant_scale is None or requant_shift is None:
            effective_scale = (x.quant.scale * weight_scale) / output_scale
            requant_scale, requant_shift = quantize_scale(effective_scale)

        out_t = Tensor(
            name=name or self._auto_name("conv"),
            height=out_h,
            width=out_w,
            channels=out_channels,
            quant=QuantParams(output_scale),
        )
        op = Conv2dOp(
            name=out_t.name,
            inputs=[x],
            output=out_t,
            weight=weight,
            bias=bias_values,
            kernel=kernel,
            stride=stride,
            padding=padding,
            activation=activation,
            clamp=clamp,
            requant_scale=requant_scale,
            requant_shift=requant_shift,
            per_channel_scale=per_channel_scale,
            pad_value=pad_value,
            weight_reuse=reused is not None,
            reused_weight_op=reused,
        )
        out_t.producer = op
        self._register_op(op)
        return out_t

    def _pool(
        self,
        x: Tensor,
        mode: str,
        kernel: tuple[int, int],
        stride: tuple[int, int],
        padding: tuple[int, int, int, int],
        pad_value: int,
        activation: Activation,
        clamp: tuple[int, int] | None,
        requant_scale: int | None,
        requant_shift: int | None,
        name: str | None,
    ) -> Tensor:
        kh, kw = kernel
        sh, sw = stride
        pt, pb, pl, pr = padding
        out_h = (x.height + pt + pb - kh) // sh + 1
        out_w = (x.width + pl + pr - kw) // sw + 1
        if out_h <= 0 or out_w <= 0:
            raise ValueError(f"{mode} pool: non-positive output dims out_h={out_h} out_w={out_w}")
        if not -128 <= pad_value <= 127:
            raise ValueError(f"{mode} pool: pad_value must be int8, got {pad_value}")

        if mode == "avg":
            if requant_scale is None or requant_shift is None:
                requant_scale, requant_shift = quantize_scale(1.0 / (kh * kw))
        else:
            requant_scale, requant_shift = requant_scale or 0, requant_shift or 0

        out_t = Tensor(
            name=name or self._auto_name(f"pool_{mode}"),
            height=out_h,
            width=out_w,
            channels=x.channels,
            quant=x.quant,
        )
        op = PoolOp(
            name=out_t.name,
            inputs=[x],
            output=out_t,
            mode=mode,
            kernel=kernel,
            stride=stride,
            padding=padding,
            pad_value=pad_value,
            activation=activation,
            clamp=clamp,
            requant_scale=requant_scale,
            requant_shift=requant_shift,
        )
        out_t.producer = op
        self._register_op(op)
        return out_t

    def pool_max(
        self,
        x: Tensor,
        *,
        kernel: tuple[int, int] = (2, 2),
        stride: tuple[int, int] = (2, 2),
        padding: tuple[int, int, int, int] = (0, 0, 0, 0),
        pad_value: int = 0,
        name: str | None = None,
    ) -> Tensor:
        """`OPCODE_POOL_MAX`: no epilogue at all in the golden model
        (`cnn_accel_model.pool_max` bypasses `bias_requantize_relu`), so
        `activation`/`clamp`/`requant` are not exposed here.

        `padding` is `(top, bottom, left, right)` and `pad_value` is the
        int8 value padded taps take -- the input tensor's quantization
        zero-point in a real network, not 0. `QuantParams` has no
        zero-point field of its own (it models symmetric quantization
        only), so this is passed explicitly rather than derived; the
        default of 0 keeps every pre-v2.1 program bit-identical.

        YOLOv8n's SPPF: `kernel=(5, 5), stride=(1, 1), padding=(2, 2, 2,
        2), pad_value=-128`."""
        return self._pool(
            x, "max", kernel, stride, padding, pad_value,
            Activation.NONE, None, None, None, name,
        )

    def pool_avg(
        self,
        x: Tensor,
        *,
        kernel: tuple[int, int] = (2, 2),
        stride: tuple[int, int] = (2, 2),
        padding: tuple[int, int, int, int] = (0, 0, 0, 0),
        pad_value: int = 0,
        activation: Activation = Activation.NONE,
        clamp: tuple[int, int] | None = None,
        requant_scale: int | None = None,
        requant_shift: int | None = None,
        name: str | None = None,
    ) -> Tensor:
        """`OPCODE_POOL_AVG`: divides by the pool area via
        `requant_scale`/`requant_shift`, defaulted to `1/(kh*kw)` unless
        overridden (matching `cnn_accel_model.pool_avg`'s documented
        "division via bias_requant"). `padding`/`pad_value` as for
        `pool_max`; note the padded taps are summed like any other, so a
        padded average is a "count-include-pad" average -- a ratified
        decision (follows from dividing through the fixed-per-descriptor
        `bias_requant` epilogue, which has no per-position divisor),
        deliberately different from TOSA's count-exclude-pad
        `avg_pool2d` (see `doc/cnn_accel_top_v2_arch.md` §5.2a, and
        `cnnc.frontend.tosa_import._INEXACT_OPS["tosa.avg_pool2d"]` for
        why the compiler refuses to lower onto this opcode)."""
        return self._pool(
            x, "avg", kernel, stride, padding, pad_value,
            activation, clamp, requant_scale, requant_shift, name,
        )

    def add(
        self,
        a: Tensor,
        b: Tensor,
        *,
        requant_scale: int | None = None,
        requant_shift: int | None = None,
        output_scale: float | None = None,
        name: str | None = None,
    ) -> Tensor:
        """`OPCODE_ADD`. `a`/`b` must share a shape. See `AddOp`/
        `reference.py` for the single-shared-requant-pair semantics this
        resolves ISA ambiguity #1 with."""
        if (a.height, a.width, a.channels) != (b.height, b.width, b.channels):
            raise ValueError(
                f"add: shape mismatch {a.height,a.width,a.channels} vs {b.height,b.width,b.channels}"
            )
        if requant_scale is None or requant_shift is None:
            eff = a.quant.scale / (output_scale if output_scale is not None else a.quant.scale)
            requant_scale, requant_shift = quantize_scale(eff)
        out_t = Tensor(
            name=name or self._auto_name("add"),
            height=a.height,
            width=a.width,
            channels=a.channels,
            quant=QuantParams(output_scale if output_scale is not None else a.quant.scale),
        )
        op = AddOp(
            name=out_t.name,
            inputs=[a, b],
            output=out_t,
            requant_scale=requant_scale,
            requant_shift=requant_shift,
        )
        out_t.producer = op
        self._register_op(op)
        return out_t

    def upsample2x(self, x: Tensor, *, name: str | None = None) -> Tensor:
        """`OPCODE_UPSAMPLE`, nearest-neighbour 2x2 replicate."""
        out_t = Tensor(
            name=name or self._auto_name("upsample"),
            height=x.height * 2,
            width=x.width * 2,
            channels=x.channels,
            quant=x.quant,
        )
        op = UpsampleOp(name=out_t.name, inputs=[x], output=out_t, factor=2)
        out_t.producer = op
        self._register_op(op)
        return out_t

    def depth_to_space(self, x: Tensor, *, factor: int = 2, name: str | None = None) -> Tensor:
        """`OPCODE_DEPTH_TO_SPACE`: pixel-shuffle `x` by `factor`, turning
        `factor**2 * C` channels into a `factor`-times-larger frame of `C`.

        Unlike `upsample2x` the output channel count is *derived*, not
        copied: `C_out = C_in / factor**2`. Both hardware preconditions are
        checked here (see `DepthToSpaceOp`) so a bad shape fails in the
        test builder, where the message is readable, rather than as an
        `ERR_BAD_GEOMETRY` from the DUT."""
        if factor != 2:
            raise ValueError(f"depth_to_space: v1 hardware implements factor 2 only, got {factor}")
        if x.channels % (factor * factor) != 0:
            raise ValueError(
                f"depth_to_space: in_channels {x.channels} is not a multiple of factor**2 = {factor * factor}"
            )
        out_channels = x.channels // (factor * factor)
        if out_channels % PLANE_CHANNELS != 0:
            raise ValueError(
                f"depth_to_space: out_channels {out_channels} must be a whole number of "
                f"{PLANE_CHANNELS}-channel activation-plane tiles -- the engine moves whole "
                "tiles and cannot gather byte lanes within one. Pad the channel count."
            )
        out_t = Tensor(
            name=name or self._auto_name("depth_to_space"),
            height=x.height * factor,
            width=x.width * factor,
            channels=out_channels,
            quant=x.quant,
        )
        op = DepthToSpaceOp(name=out_t.name, inputs=[x], output=out_t, factor=factor)
        out_t.producer = op
        self._register_op(op)
        return out_t

    def copy(self, x: Tensor, *, name: str | None = None) -> Tensor:
        """`OPCODE_COPY`: local-to-local (or any-space-to-any-space)
        byte copy, shape/quant preserved exactly."""
        out_t = Tensor(
            name=name or self._auto_name("copy"), height=x.height, width=x.width, channels=x.channels, quant=x.quant
        )
        op = CopyOp(name=out_t.name, inputs=[x], output=out_t)
        out_t.producer = op
        self._register_op(op)
        return out_t

    # -- channel concatenation / splitting (no hardware, see below) --------

    def split(self, x: Tensor, sizes: list[int], *, names: list[str] | None = None) -> list[Tensor]:
        """Split `x` along channels into `len(sizes)` tensors -- **free**:
        no opcode, no instruction, no byte moved.

        The section-3 activation layout is channel-plane-major
        (`((c_tile * H + y) * W + x) * T + t`, `T = 8`), so `x` is
        `ceil(C/T)` contiguous planes of `H*W*T` bytes and a channel
        range starting at a multiple of `T` is just a contiguous
        sub-range of those planes. Each returned tensor is therefore a
        *view* of `x` at `addr(x) + plane_index * H * W * T`, which
        `planner.py` resolves and `program.py` then encodes as an
        ordinary `in_addr` -- indistinguishable, to the hardware, from a
        tensor that was produced there in the first place.

        Every interior boundary (`sizes[0]`, `sizes[0]+sizes[1]`, ...)
        must be a multiple of `T = 8`; only the *last* part may have a
        channel count that is not, because only its trailing lanes
        coincide with `x`'s own zero-padded lanes rather than with
        another part's real data.

        YOLOv8n's C2f splits a multiple-of-16 channel count in half, so
        every boundary it needs is a multiple of 8.
        """
        if not sizes:
            raise ValueError(f"split of '{x.name}': `sizes` must not be empty")
        for index, size in enumerate(sizes):
            if size <= 0:
                raise ValueError(
                    f"split of '{x.name}': every part must have at least one channel, "
                    f"but sizes[{index}] = {size}"
                )
        if sum(sizes) != x.channels:
            raise ValueError(
                f"split of '{x.name}': sizes {list(sizes)} sum to {sum(sizes)}, but "
                f"'{x.name}' has {x.channels} channels -- a split must cover the tensor exactly"
            )
        if names is not None and len(names) != len(sizes):
            raise ValueError(
                f"split of '{x.name}': {len(names)} names given for {len(sizes)} parts"
            )

        boundary = 0
        parts: list[Tensor] = []
        for index, size in enumerate(sizes):
            if boundary % PLANE_CHANNELS != 0:
                raise ValueError(
                    f"split of '{x.name}': part {index} starts at channel {boundary}, which is "
                    f"not a multiple of the {PLANE_CHANNELS}-channel activation plane. "
                    f"A split is only free at a plane boundary; sizes {list(sizes)} would need "
                    f"a channel shuffle. Round the preceding part(s) to a multiple of "
                    f"{PLANE_CHANNELS}, or split into plane-aligned pieces and recombine them."
                )
            part = Tensor(
                name=(names[index] if names is not None else self._auto_name("split")),
                height=x.height,
                width=x.width,
                channels=size,
                quant=x.quant,
                alias_parent=x,
                alias_plane_offset=boundary // PLANE_CHANNELS,
                alias_role="slice",
            )
            self.tensors.append(part)
            parts.append(part)
            boundary += size
        return parts

    def concat(self, tensors: list[Tensor], *, name: str | None = None) -> Tensor:
        """Concatenate `tensors` along channels -- **free** whenever the
        planner can place each operand's producer output directly into
        the right slice of one buffer.

        Same layout argument as `split`: the result's plane list is
        operand 0's planes followed by operand 1's, and so on, so if each
        producer is simply told to write at `addr(result) + plane_offset
        * H * W * T` the concatenation has already happened by the time
        the last producer retires. No opcode, no instruction, and no
        extra DDR traffic.

        Two things stop an operand being placed that way, and both fall
        back to an explicit `COPY` (`model.copy`) into the slice:

        * it already lives inside some *other* buffer (it is a `split`
          view, or an operand of an earlier `concat`) -- a tensor cannot
          be in two places at once;
        * it is a graph input or a graph output, whose address is fixed
          by the DDR region layout rather than chosen by the planner.

        The one exception is the round trip `concat(split(t))`: when the
        operands are already contiguous, in order, inside one common
        parent, the result is returned as a plain view of that parent and
        still costs nothing.

        Every operand but the last must have a channel count that is a
        multiple of `T = 8`, for the same reason `split`'s interior
        boundaries must be: a non-plane-aligned operand's producer would
        zero the padding lanes it shares with the next operand's data.
        """
        if len(tensors) < 2:
            raise ValueError(
                f"concat needs at least two tensors, got {len(tensors)} -- "
                "concatenating one tensor is a no-op, say nothing instead"
            )
        first = tensors[0]
        for other in tensors[1:]:
            if (other.height, other.width) != (first.height, first.width):
                raise ValueError(
                    f"concat: spatial shape mismatch -- '{first.name}' is "
                    f"{first.height}x{first.width} (HxW) but '{other.name}' is "
                    f"{other.height}x{other.width}. Channel concatenation requires every "
                    "operand to have identical height and width."
                )
        for index, t in enumerate(tensors[:-1]):
            if t.channels % PLANE_CHANNELS != 0:
                raise ValueError(
                    f"concat: operand {index} '{t.name}' has {t.channels} channels, which is "
                    f"not a multiple of the {PLANE_CHANNELS}-channel activation plane. "
                    f"Only the LAST operand may be unaligned, because every other operand's "
                    f"padding lanes would overlap the next operand's real channels. "
                    f"Pad '{t.name}' to {(-(-t.channels // PLANE_CHANNELS)) * PLANE_CHANNELS} "
                    "channels, or reorder the concatenation so the unaligned operand is last."
                )

        total_channels = sum(t.channels for t in tensors)
        out_name = name or self._auto_name("concat")

        reviewed = self._concat_as_review(tensors, out_name, total_channels)
        if reviewed is not None:
            self.tensors.append(reviewed)
            return reviewed

        out_t = Tensor(
            name=out_name,
            height=first.height,
            width=first.width,
            channels=total_channels,
            quant=first.quant,
        )
        self.tensors.append(out_t)

        plane = 0
        for t in tensors:
            operand = t if self._can_be_concat_part(t) else self.copy(t, name=f"{out_name}_copy{plane}")
            operand.alias_parent = out_t
            operand.alias_plane_offset = plane
            operand.alias_role = "part"
            out_t.alias_parts.append(operand)
            plane += golden.activation_plane_count(t.channels)
        return out_t

    @staticmethod
    def _can_be_concat_part(t: Tensor) -> bool:
        """Can `t`'s bytes simply *be* the concat result's slice?

        Only if nothing else already dictates where those bytes live:
        `t` must own its buffer (`alias_parent is None`), must be
        produced by something whose output address the planner is free to
        choose (an op, or -- for a nested concat -- its own parts), and
        must not be pinned to a DDR region by being a graph input or a
        graph output."""
        if t.alias_parent is not None:
            return False
        if t.is_input or t.is_output:
            return False
        return t.producer is not None or bool(t.alias_parts)

    @staticmethod
    def _concat_as_review(tensors: list[Tensor], out_name: str, total_channels: int) -> Tensor | None:
        """`concat(split(p))` and friends: if every operand is already a
        view of one common parent and they sit contiguously, in order,
        the concatenation is that byte range and needs no buffer of its
        own. Returns the view tensor, or `None` when the general path
        applies."""
        first = tensors[0]
        if first.alias_parent is None:
            return None
        root = alias_root(first)
        start = alias_plane_offset_total(first)
        expected = start
        for t in tensors:
            if t.alias_parent is None or alias_root(t) is not root:
                return None
            if alias_plane_offset_total(t) != expected:
                return None
            expected += golden.activation_plane_count(t.channels)
        if expected * PLANE_CHANNELS > root.plane_count * PLANE_CHANNELS:
            return None
        return Tensor(
            name=out_name,
            height=first.height,
            width=first.width,
            channels=total_channels,
            quant=first.quant,
            alias_parent=root,
            alias_plane_offset=start,
            alias_role="slice",
        )

    # -- spatial tiling helpers (see `tiler.py`) ---------------------------

    def register_prebuilt_op(self, op: Op) -> Op:
        """Attach an `Op` this module did not build, wiring up the same
        `consumers`/`tensors` bookkeeping every builder method does.

        `tiler.py` constructs its clones directly rather than calling
        `conv2d`/`pool_max`/..., for one reason: those methods draw
        weights, biases and scale tables from the model's RNG, and a
        strip clone must reuse the *original* op's constants byte for
        byte or the tiled program computes a different (if equally valid)
        network and the tiled-vs-untiled oracle has nothing to compare.
        Op construction is a dataclass call; only the graph bookkeeping
        is worth sharing, and this is it."""
        self._register_op(op)
        return op

    def copy_rows(
        self,
        src: Tensor,
        rows: RowRange,
        *,
        into: Tensor | None = None,
        at: RowRange | None = None,
        name: str | None = None,
    ) -> Tensor:
        """Move rows `rows` of `src` into `into`'s rows `at` (or into a
        fresh compact tensor of `rows.rows` rows when `into` is `None`).

        The two forms are the two halves of tiling. `into=None` *extracts*
        a window -- the group-input LOAD of a strip, and the row
        alignment a join needs when one operand's strip is taller than
        the join's output. `into=<tensor>` *stores* a strip back into a
        full-resolution buffer at a row offset, which is how `S` strips
        assemble one group output.

        `at` defaults to `rows` (same rows at both ends), which is what
        the store form of a strip whose destination shares the source's
        coordinate system wants; the extract form always lands at row 0
        of its fresh buffer.

        No opcode is chosen here: `planner.py` resolves the two operand
        spaces and `program.py` picks `LOAD`/`STORE`/`COPY` from them,
        the same way it already does for a spill or a reload."""
        if rows.rows <= 0:
            raise ValueError(
                f"copy_rows of '{src.name}': {rows} is empty -- a row copy must move at "
                "least one row (an empty strip is a tiler bug, not a legal program)"
            )
        if rows.r0 < 0 or rows.r1 > src.height:
            raise ValueError(
                f"copy_rows of '{src.name}': {rows} is outside the tensor's "
                f"{src.height} rows"
            )

        if into is None:
            dst = Tensor(
                name=name or self._auto_name("rowcopy"),
                height=rows.rows,
                width=src.width,
                channels=src.channels,
                quant=src.quant,
            )
            dst_rows = RowRange(0, rows.rows)
        else:
            dst = into
            dst_rows = at if at is not None else rows
            if dst_rows.rows != rows.rows:
                raise ValueError(
                    f"copy_rows into '{into.name}': source {rows} is {rows.rows} rows but "
                    f"destination {dst_rows} is {dst_rows.rows} -- a row copy moves rows, "
                    "it does not resample them"
                )
            if dst_rows.r0 < 0 or dst_rows.r1 > into.height:
                raise ValueError(
                    f"copy_rows into '{into.name}': {dst_rows} is outside the tensor's "
                    f"{into.height} rows"
                )

        if src.width != dst.width or src.plane_count != dst.plane_count:
            raise ValueError(
                f"copy_rows '{src.name}' -> '{dst.name}': the two ends must agree on width "
                f"and plane count (got {src.width}x{src.plane_count} planes vs "
                f"{dst.width}x{dst.plane_count}). A row copy moves whole plane-rows; it "
                "never reshapes channels and never splits a plane."
            )

        op = RowCopyOp(name=dst.name, inputs=[src], output=dst, src_rows=rows, dst_rows=dst_rows)
        if into is None:
            # Only the extract form owns its output. A store form's
            # destination has several writers (one per strip) and
            # therefore no single `producer` -- `planner.py` counts
            # writers by walking `Model.ops`, exactly so this works.
            dst.producer = op
        self._register_op(op)
        return dst

    def add_planewise(
        self,
        a: Tensor,
        b: Tensor,
        *,
        requant_scale: int | None = None,
        requant_shift: int | None = None,
        output_scale: float | None = None,
        name: str | None = None,
    ) -> Tensor:
        """`add(a, b)`, but emitted as one `ADD` **per activation plane**
        and re-concatenated -- arithmetically identical, and the only
        form a tiled program may use.

        `cnn_accel_elementwise.vhd` issues an `ADD` as a single request
        per operand covering the whole tensor (`in_w*in_h*T*8` bytes),
        while `cnn_accel_tensor_mem` serves any one request from the
        single bank its address decodes to. A multi-plane strip buffer is
        deliberately allowed to span banks at plane granularity
        (`Tensor.confine_unit_bytes`), so a whole-tensor `ADD` request
        over one would be silently clamped. Splitting the add along
        planes -- which is free, `split`/`concat` are pure aliasing --
        keeps every request inside one plane and therefore inside one
        bank.

        Degenerates to a plain `add` for a single-plane tensor, so the
        untiled catalogue is unaffected."""
        if (a.height, a.width, a.channels) != (b.height, b.width, b.channels):
            raise ValueError(
                f"add_planewise: shape mismatch {a.height, a.width, a.channels} vs "
                f"{b.height, b.width, b.channels}"
            )
        out_name = name or self._auto_name("add")
        if a.plane_count == 1:
            return self.add(
                a,
                b,
                requant_scale=requant_scale,
                requant_shift=requant_shift,
                output_scale=output_scale,
                name=out_name,
            )

        sizes = _plane_sizes(a.channels)
        a_planes = self.split(a, sizes, names=[f"{out_name}_a{i}" for i in range(len(sizes))])
        b_planes = self.split(b, sizes, names=[f"{out_name}_b{i}" for i in range(len(sizes))])
        sums = [
            self.add(
                ap,
                bp,
                requant_scale=requant_scale,
                requant_shift=requant_shift,
                output_scale=output_scale,
                name=f"{out_name}_p{i}",
            )
            for i, (ap, bp) in enumerate(zip(a_planes, b_planes))
        ]
        return self.concat(sums, name=out_name)

    def act(self, x: Tensor, lut: list[int] | None = None, *, name: str | None = None) -> Tensor:
        """`OPCODE_ACT`. `lut[raw_byte] -> int8` for `raw_byte` in
        `0..255` (i.e. indexed by the *unsigned* byte representation of
        the signed input, matching a hardware LUT addressed by the raw
        activation byte); defaults to a ReLU LUT if omitted."""
        if lut is None:
            lut = [max(0, b - 256 if b >= 128 else b) for b in range(256)]
        if len(lut) != 256:
            raise ValueError(f"act: lut must have exactly 256 entries, got {len(lut)}")
        out_t = Tensor(
            name=name or self._auto_name("act"), height=x.height, width=x.width, channels=x.channels, quant=x.quant
        )
        op = ActOp(name=out_t.name, inputs=[x], output=out_t, lut=list(lut))
        out_t.producer = op
        self._register_op(op)
        return out_t


def _plane_sizes(channels: int) -> list[int]:
    """`channels` cut into one entry per activation plane: `T` channels
    each, with a short last entry when `channels` is not a multiple of
    `T`. The channel counts a `split` needs to name every plane of a
    tensor individually (`Model.add_planewise`)."""
    sizes = [PLANE_CHANNELS] * (channels // PLANE_CHANNELS)
    if channels % PLANE_CHANNELS:
        sizes.append(channels % PLANE_CHANNELS)
    return sizes


class _Rng:
    """Thin wrapper around `random.Random(seed)` so every random draw
    used by `Model` funnels through one place, named by what it is
    generating (keeps `Model`'s builder methods free of magic-number
    ranges)."""

    def __init__(self, seed: int) -> None:
        import random

        self._r = random.Random(seed)

    def int8_list(self, n: int, low: int = -128, high: int = 127) -> list[int]:
        return [self._r.randint(low, high) for _ in range(n)]

    def bias_list(self, n: int, magnitude: int = 2000) -> list[int]:
        return [self._r.randint(-magnitude, magnitude) for _ in range(n)]

    def scale_table(self, n: int) -> list[tuple[int, int]]:
        return [quantize_scale(self._r.uniform(1e-3, 2.0)) for _ in range(n)]


__all__ = [
    "PLANE_CHANNELS",
    "RowRange",
    "StripOrigin",
    "alias_root",
    "alias_plane_offset_total",
    "alias_byte_offset",
    "QuantParams",
    "Tensor",
    "Activation",
    "Op",
    "Conv2dOp",
    "PoolOp",
    "AddOp",
    "UpsampleOp",
    "DepthToSpaceOp",
    "CopyOp",
    "ActOp",
    "RowCopyOp",
    "Model",
    "quantize_scale",
]
