"""Hand-written network builder -- deliberately **not** TOSA/MLIR-based.

This is the object-oriented "model-building framework" a test author uses
to construct a small tensor program directly in Python: tensors carry a
shape and a quantization scale, and operations (`conv2d`, `add`,
`upsample2x`, `pool_max`/`pool_avg`, `copy`, `act`) are chained purely by
dataflow (an op's inputs are the `Tensor` objects returned by earlier
calls). `planner.py` turns the resulting graph into a residency-aware
program; `reference.py` executes it bit-exactly; `program.py` lowers it to
`DescV2`s and a `MemoryImage`.

Authoritative source for op semantics: `doc/cnn_accel_top_v2_arch.md`
section 5 (opcode table, W0 flags). The actual arithmetic is never
reimplemented here -- every numeric op is a thin wrapper that
`reference.py` later drives through `cnn_accel_model.py`'s existing
`conv2d`/`pool_max`/`pool_avg`/`bias_requantize_relu`. This module only
knows shapes, random data and which HW fields an op needs.

Weights/biases/inputs/per-channel scale tables are generated by a single
`random.Random(seed)` instance owned by the `Model`, consumed in
call order, so two `Model` runs built with the same seed (and the same
sequence of builder calls) produce byte-identical data -- the
determinism the spec's test list asks for.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum, auto
from itertools import count

import cnn_accel_model as golden

# ---------------------------------------------------------------------------
# Compiler-side helper: real scale -> (requant_scale, requant_shift).
#
# This has NO counterpart in cnn_accel_model.py: that module only knows how
# to *apply* a already-chosen (multiplier, shift) pair
# (`bias_requantize_relu`/`round_shift_right_signed`), which is the
# hardware-bit-exact half and is reused verbatim. Computing suitable
# fixed-point parameters from a floating-point ratio is a compiler
# concern with no hardware behaviour to be bit-exact against, so it is
# implemented here, once, rather than approximated ad hoc in every test.
# ---------------------------------------------------------------------------


def quantize_scale(real_scale: float, *, max_shift: int = 200) -> tuple[int, int]:
    """Choose a signed Q15 `requant_scale` (W9) and `requant_shift` (W10,
    `0..max_shift`) such that

        requant_scale / 2**(15 + requant_shift) ~= real_scale

    using as many mantissa bits as the 32-bit signed `requant_scale`
    field allows (`frexp`-normalize `real_scale` into `[0.5, 1)` times a
    power of two, then keep 32 bits of that mantissa), the same idea as
    TFLite's `QuantizeMultiplier` adapted to this ISA's Q15-plus-extra-
    shift encoding instead of a plain Q31 multiplier. Only used by
    `Model`'s builder methods to turn a friendly `output_scale`/
    `weight_scale` ratio into descriptor fields; never consulted by
    `reference.py`, which only ever *applies* the resulting
    `(requant_scale, requant_shift)` via `cnn_accel_model.
    bias_requantize_relu` (reused, not reimplemented)."""
    if real_scale <= 0:
        raise ValueError(f"real_scale must be positive, got {real_scale}")

    mantissa, exponent = math.frexp(real_scale)  # real_scale == mantissa * 2**exponent, 0.5 <= mantissa < 1
    shift = 16 - exponent
    if shift < 0:
        shift = 0
    if shift > max_shift:
        shift = max_shift

    multiplier = round(real_scale * (2 ** (15 + shift)))
    # Rounding at the mantissa's 0.5 boundary (or a large max_shift clamp)
    # can push the multiplier to/past 2**31; renormalize downward rather
    # than encode a value that would not round-trip through the signed
    # 32-bit `requant_scale` field.
    while multiplier >= 2**31 and shift > 0:
        multiplier = round(multiplier / 2)
        shift -= 1
    multiplier = min(multiplier, 2**31 - 1)
    return multiplier, shift


# ---------------------------------------------------------------------------
# Tensors and quantization.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class QuantParams:
    """Per-tensor symmetric int8 quantization: `real_value = int8_value *
    scale`. No zero-point: nowhere in the HW epilogue
    (`cnn_accel_model.bias_requantize_relu`) is a per-element zero-point
    subtracted -- the only additive term is the integer `output_offset`
    applied once, after the shift, to the whole lane. A caller targeting
    an asymmetric TOSA tensor must fold its zero-point into
    `output_offset` itself; `QuantParams` intentionally has no field that
    would suggest otherwise."""

    scale: float

    def __post_init__(self) -> None:
        if self.scale <= 0:
            raise ValueError(f"quant scale must be positive, got {self.scale}")


@dataclass
class Tensor:
    """One node in the dataflow graph. `height/width/channels` is the
    LOGICAL HWC shape `cnn_accel_model.conv2d`/`pool_*` operate on --
    never the DDR channel-tiled-plane layout, which is a `reference.py`/
    `program.py` concern applied only at the memory boundary."""

    name: str
    height: int
    width: int
    channels: int
    quant: QuantParams
    producer: "Op | None" = None
    is_input: bool = False
    is_output: bool = False
    #: LOGICAL HWC int8 values, `-128..127`. Populated eagerly (from the
    #: model's RNG) for `is_input` tensors; populated for every other
    #: tensor only after `reference.run_reference` executes its producer.
    data: list[int] | None = None
    #: Indices into `Model.ops`, in the chronological order this tensor
    #: was consumed -- the liveness information `planner.py` needs and
    #: hardware deliberately does not track (section 3.1).
    consumers: list[int] = field(default_factory=list)

    @property
    def size_bytes(self) -> int:
        """DDR/LOCAL_TENSOR byte footprint of this tensor in the
        section-3 channel-tiled-plane layout (identical in both spaces)."""
        return golden.activation_bytes(self.width, self.height, self.channels)


class Activation(Enum):
    """Epilogue activation choice for a compute op, orthogonal to
    `clamp` (section 5.1: `CLAMP_EN` set means `clamp_min`/`clamp_max`
    are used and `RELU_EN` is ignored; `CLAMP_EN` clear falls back to the
    legacy `RELU_EN`-selected `[0 or -128, 127]` range -- see
    `cnn_accel_model.bias_requantize_relu`)."""

    NONE = auto()
    RELU = auto()


# ---------------------------------------------------------------------------
# Ops. Each carries everything `reference.py`/`program.py` need: shapes
# live on the `Tensor`s, so an `Op` only carries the extra per-instruction
# parameters (kernel/stride/pad, weights, requant, ...).
# ---------------------------------------------------------------------------


@dataclass
class Op:
    name: str
    inputs: list[Tensor]
    output: Tensor


@dataclass
class Conv2dOp(Op):
    """`OPCODE_CONV2D`. `weight` is LOGICAL OHWI (module docstring of
    `cnn_accel_model.py`); `bias` is one int32 per output channel or
    `None` (`BIAS_EN` clear)."""

    weight: list[int]
    bias: list[int] | None
    kernel: tuple[int, int]
    stride: tuple[int, int]
    padding: tuple[int, int, int, int]  # (top, bottom, left, right)
    activation: Activation
    clamp: tuple[int, int] | None
    requant_scale: int
    requant_shift: int
    output_offset: int = 0
    per_channel_scale: list[tuple[int, int]] | None = None
    #: ISA v2.0 `WEIGHT_REUSE` (R6): when set, this op's weight/bias/
    #: scale buffers are already resident from `reused_weight_op` and
    #: must not be refetched -- `planner.py` charges it zero weight
    #: bytes, `program.py` points its weight/bias/scale addresses at
    #: `reused_weight_op`'s own allocation instead of making a new one.
    weight_reuse: bool = False
    reused_weight_op: "Conv2dOp | None" = None

    def flags(self) -> int:
        """W0 `flags` byte (section 5.1) for this op's `CONV2D`
        descriptor. The single place this is computed -- `reference.py`
        and `program.py` both call this rather than each re-deriving the
        same bits from `activation`/`clamp`/`bias`/`padding`/
        `per_channel_scale`/`weight_reuse`, so the executor and the
        descriptor emitter cannot silently disagree about which
        epilogue stages are enabled."""
        f = 0
        if self.bias is not None:
            f |= 1 << golden.FLAG_BIAS_EN
        f |= 1 << golden.FLAG_REQUANT_EN
        if self.clamp is not None:
            f |= 1 << golden.FLAG_CLAMP_EN
        elif self.activation == Activation.RELU:
            f |= 1 << golden.FLAG_RELU_EN
        if self.per_channel_scale is not None:
            f |= 1 << golden.FLAG_PER_CHANNEL_EN
        if any(self.padding):
            f |= 1 << golden.FLAG_PAD_EN
        if self.weight_reuse:
            f |= 1 << golden.FLAG_WEIGHT_REUSE
        return f

    def weight_layer_desc(self) -> golden.LayerDesc:
        """A minimal `cnn_accel_model.LayerDesc` carrying only the fields
        `pack_weights_for_hw`/`packed_weight_count`/`pack_bias_for_hw`/
        `pack_scale_table_for_hw` actually read (`in_channels`,
        `out_channels`, `kernel_h`, `kernel_w`). The single place both
        `planner.py` (byte-count prediction) and `program.py` (actual
        packing) build this from, so the two can never drift apart."""
        x = self.inputs[0]
        return golden.LayerDesc(
            opcode=golden.OPCODE_CONV2D,
            in_channels=x.channels,
            out_channels=self.output.channels,
            kernel_h=self.kernel[0],
            kernel_w=self.kernel[1],
        )


@dataclass
class PoolOp(Op):
    """`OPCODE_POOL_MAX`/`OPCODE_POOL_AVG`.

    ISA v2.1: pooling now has padding, reusing `CONV2D`'s own
    `FLAG_PAD_EN` + `pad_top/bottom/left/right` fields, plus `pad_value`
    -- the int8 value padded taps take, which for a real quantized tensor
    is its zero-point and NOT 0 (see `cnn_accel_model._pool_windows`).
    YOLOv8n's SPPF block is the motivating shape: 5x5 max pool, stride 1,
    padding 2, on a tensor with zero_point = -128."""

    mode: str  # "max" | "avg"
    kernel: tuple[int, int]
    stride: tuple[int, int]
    padding: tuple[int, int, int, int] = (0, 0, 0, 0)  # (top, bottom, left, right)
    pad_value: int = 0
    activation: Activation = Activation.NONE
    clamp: tuple[int, int] | None = None
    requant_scale: int = 0
    requant_shift: int = 0
    output_offset: int = 0

    def flags(self) -> int:
        """W0 `flags` byte for this op's `POOL_MAX`/`POOL_AVG`
        descriptor -- see `Conv2dOp.flags` for why this is centralized
        here rather than re-derived by each caller. `POOL_AVG` always
        sets `REQUANT_EN` (division is implemented as the epilogue's
        requantize step, section 5.2); `POOL_MAX` never does (integer
        max has no scale to correct)."""
        f = 0
        if self.mode == "avg":
            f |= 1 << golden.FLAG_REQUANT_EN
        if self.clamp is not None:
            f |= 1 << golden.FLAG_CLAMP_EN
        elif self.activation == Activation.RELU:
            f |= 1 << golden.FLAG_RELU_EN
        if any(self.padding):
            f |= 1 << golden.FLAG_PAD_EN
        return f


@dataclass
class AddOp(Op):
    """`OPCODE_ADD`: `dst = sat_i8(requant(src0) + requant(src1))`
    (section 5.2), one shared `(requant_scale, requant_shift)` pair
    applied identically to both operands -- see `reference.py`'s
    docstring for why (the descriptor has only one such pair for `ADD`,
    section 5.1's ambiguity resolved there)."""

    requant_scale: int
    requant_shift: int


@dataclass
class UpsampleOp(Op):
    """`OPCODE_UPSAMPLE`: nearest-neighbour replicate, factor 2 only
    (section 12 limitation 5 -- the only mode YOLOv8n needs)."""

    factor: int = 2


@dataclass
class CopyOp(Op):
    """`OPCODE_COPY`: opaque byte copy, `xfer_bytes` long. Never
    interprets its payload as activation elements (no pack/unpack at
    either end), which is why it is legal between any two spaces/
    addresses of matching length regardless of tensor shape."""


@dataclass
class ActOp(Op):
    """`OPCODE_ACT`: standalone 256-entry signed int8 -> int8 LUT."""

    lut: list[int]


# ---------------------------------------------------------------------------
# Model: the graph builder.
# ---------------------------------------------------------------------------


class Model:
    """A small, explicit dataflow graph plus the deterministic RNG that
    fills in every op's random weights/biases/inputs/per-channel scale
    tables. Two `Model(seed=S)` built by an identical sequence of calls
    are byte-identical; a different `seed` (almost certainly) is not --
    exercised directly by `tests/test_model.py`'s determinism test."""

    def __init__(self, seed: int, name: str = "model") -> None:
        self.seed = seed
        self.name = name
        self._rng = _Rng(seed)
        self.ops: list[Op] = []
        self.tensors: list[Tensor] = []
        self.inputs: list[Tensor] = []
        self.outputs: list[Tensor] = []
        self._counter = count()

    # -- naming / bookkeeping ---------------------------------------------

    def _auto_name(self, prefix: str) -> str:
        return f"{prefix}{next(self._counter)}"

    def _register_op(self, op: Op) -> None:
        op_index = len(self.ops)
        for t in op.inputs:
            t.consumers.append(op_index)
        self.ops.append(op)
        self.tensors.append(op.output)

    # -- graph inputs/outputs ----------------------------------------------

    def input(
        self, height: int, width: int, channels: int, scale: float = 1.0, name: str | None = None
    ) -> Tensor:
        """A tensor materialized in DDR before the program starts (the
        residency policy's one legitimate "initial input" round trip).
        Its data is generated now, deterministically, from the model's
        RNG."""
        t = Tensor(
            name=name or self._auto_name("input"),
            height=height,
            width=width,
            channels=channels,
            quant=QuantParams(scale),
            is_input=True,
        )
        t.data = self._rng.int8_list(height * width * channels)
        self.inputs.append(t)
        self.tensors.append(t)
        return t

    def output(self, tensor: Tensor) -> Tensor:
        """Mark `tensor` a graph output: `planner.py` always lands it in
        the DDR `OUTPUTS` region (never `LOCAL_TENSOR`), matching the
        residency policy's "DDR is backing storage only... for... final
        outputs"."""
        if tensor.is_output:
            return tensor
        tensor.is_output = True
        self.outputs.append(tensor)
        return tensor

    # -- ops -----------------------------------------------------------------

    def conv2d(
        self,
        x: Tensor,
        out_channels: int,
        *,
        kernel: tuple[int, int] = (3, 3),
        stride: tuple[int, int] = (1, 1),
        padding: tuple[int, int, int, int] = (0, 0, 0, 0),
        bias: bool = True,
        activation: Activation = Activation.RELU,
        clamp: tuple[int, int] | None = None,
        requant_scale: int | None = None,
        requant_shift: int | None = None,
        weight_scale: float = 1.0,
        output_scale: float = 1.0,
        per_channel: bool = False,
        weight_reuse_from: Tensor | None = None,
        name: str | None = None,
    ) -> Tensor:
        """`CONV2D`. `padding` is `(top, bottom, left, right)`.

        If `requant_scale`/`requant_shift` are both omitted they are
        derived from `x.quant.scale * weight_scale / output_scale` via
        `quantize_scale` -- convenient for a test that only cares about
        shapes, while boundary-rounding tests can still pass exact
        integers.

        `weight_reuse_from` names the OUTPUT tensor of an earlier
        `conv2d` call whose weight/bias/scale-table this op reuses
        verbatim (ISA v2.0 `WEIGHT_REUSE`, R6); geometry
        (`in_channels`/`out_channels`/`kernel`) must match, checked here
        rather than left for `program.py` to discover late."""
        kh, kw = kernel
        sh, sw = stride
        pt, pb, pl, pr = padding
        out_h = (x.height + pt + pb - kh) // sh + 1
        out_w = (x.width + pl + pr - kw) // sw + 1
        if out_h <= 0 or out_w <= 0:
            raise ValueError(f"conv2d: non-positive output dims out_h={out_h} out_w={out_w}")

        if weight_reuse_from is not None:
            reused = weight_reuse_from.producer
            if not isinstance(reused, Conv2dOp):
                raise TypeError("weight_reuse_from must be the output of an earlier conv2d")
            if reused.inputs[0].channels != x.channels or reused.kernel != kernel:
                raise ValueError(
                    "weight_reuse_from geometry mismatch: reused conv has "
                    f"in_channels={reused.inputs[0].channels} kernel={reused.kernel}, "
                    f"this conv wants in_channels={x.channels} kernel={kernel}"
                )
            if reused.output.channels != out_channels:
                raise ValueError(
                    f"weight_reuse_from has out_channels={reused.output.channels}, "
                    f"this conv wants out_channels={out_channels}"
                )
            weight, bias_values, per_channel_scale = reused.weight, reused.bias, reused.per_channel_scale
        else:
            reused = None
            weight = self._rng.int8_list(out_channels * kh * kw * x.channels, low=-127, high=127)
            bias_values = self._rng.bias_list(out_channels) if bias else None
            per_channel_scale = self._rng.scale_table(out_channels) if per_channel else None

        if requant_scale is None or requant_shift is None:
            effective_scale = (x.quant.scale * weight_scale) / output_scale
            requant_scale, requant_shift = quantize_scale(effective_scale)

        out_t = Tensor(
            name=name or self._auto_name("conv"),
            height=out_h,
            width=out_w,
            channels=out_channels,
            quant=QuantParams(output_scale),
        )
        op = Conv2dOp(
            name=out_t.name,
            inputs=[x],
            output=out_t,
            weight=weight,
            bias=bias_values,
            kernel=kernel,
            stride=stride,
            padding=padding,
            activation=activation,
            clamp=clamp,
            requant_scale=requant_scale,
            requant_shift=requant_shift,
            per_channel_scale=per_channel_scale,
            weight_reuse=reused is not None,
            reused_weight_op=reused,
        )
        out_t.producer = op
        self._register_op(op)
        return out_t

    def _pool(
        self,
        x: Tensor,
        mode: str,
        kernel: tuple[int, int],
        stride: tuple[int, int],
        padding: tuple[int, int, int, int],
        pad_value: int,
        activation: Activation,
        clamp: tuple[int, int] | None,
        requant_scale: int | None,
        requant_shift: int | None,
        name: str | None,
    ) -> Tensor:
        kh, kw = kernel
        sh, sw = stride
        pt, pb, pl, pr = padding
        out_h = (x.height + pt + pb - kh) // sh + 1
        out_w = (x.width + pl + pr - kw) // sw + 1
        if out_h <= 0 or out_w <= 0:
            raise ValueError(f"{mode} pool: non-positive output dims out_h={out_h} out_w={out_w}")
        if not -128 <= pad_value <= 127:
            raise ValueError(f"{mode} pool: pad_value must be int8, got {pad_value}")

        if mode == "avg":
            if requant_scale is None or requant_shift is None:
                requant_scale, requant_shift = quantize_scale(1.0 / (kh * kw))
        else:
            requant_scale, requant_shift = requant_scale or 0, requant_shift or 0

        out_t = Tensor(
            name=name or self._auto_name(f"pool_{mode}"),
            height=out_h,
            width=out_w,
            channels=x.channels,
            quant=x.quant,
        )
        op = PoolOp(
            name=out_t.name,
            inputs=[x],
            output=out_t,
            mode=mode,
            kernel=kernel,
            stride=stride,
            padding=padding,
            pad_value=pad_value,
            activation=activation,
            clamp=clamp,
            requant_scale=requant_scale,
            requant_shift=requant_shift,
        )
        out_t.producer = op
        self._register_op(op)
        return out_t

    def pool_max(
        self,
        x: Tensor,
        *,
        kernel: tuple[int, int] = (2, 2),
        stride: tuple[int, int] = (2, 2),
        padding: tuple[int, int, int, int] = (0, 0, 0, 0),
        pad_value: int = 0,
        name: str | None = None,
    ) -> Tensor:
        """`OPCODE_POOL_MAX`: no epilogue at all in the golden model
        (`cnn_accel_model.pool_max` bypasses `bias_requantize_relu`), so
        `activation`/`clamp`/`requant` are not exposed here.

        `padding` is `(top, bottom, left, right)` and `pad_value` is the
        int8 value padded taps take -- the input tensor's quantization
        zero-point in a real network, not 0. `QuantParams` has no
        zero-point field of its own (it models symmetric quantization
        only), so this is passed explicitly rather than derived; the
        default of 0 keeps every pre-v2.1 program bit-identical.

        YOLOv8n's SPPF: `kernel=(5, 5), stride=(1, 1), padding=(2, 2, 2,
        2), pad_value=-128`."""
        return self._pool(
            x, "max", kernel, stride, padding, pad_value,
            Activation.NONE, None, None, None, name,
        )

    def pool_avg(
        self,
        x: Tensor,
        *,
        kernel: tuple[int, int] = (2, 2),
        stride: tuple[int, int] = (2, 2),
        padding: tuple[int, int, int, int] = (0, 0, 0, 0),
        pad_value: int = 0,
        activation: Activation = Activation.NONE,
        clamp: tuple[int, int] | None = None,
        requant_scale: int | None = None,
        requant_shift: int | None = None,
        name: str | None = None,
    ) -> Tensor:
        """`OPCODE_POOL_AVG`: divides by the pool area via
        `requant_scale`/`requant_shift`, defaulted to `1/(kh*kw)` unless
        overridden (matching `cnn_accel_model.pool_avg`'s documented
        "division via bias_requant"). `padding`/`pad_value` as for
        `pool_max`; note the padded taps are summed like any other, so a
        padded average is a "count-include-pad" average."""
        return self._pool(
            x, "avg", kernel, stride, padding, pad_value,
            activation, clamp, requant_scale, requant_shift, name,
        )

    def add(
        self,
        a: Tensor,
        b: Tensor,
        *,
        requant_scale: int | None = None,
        requant_shift: int | None = None,
        output_scale: float | None = None,
        name: str | None = None,
    ) -> Tensor:
        """`OPCODE_ADD`. `a`/`b` must share a shape. See `AddOp`/
        `reference.py` for the single-shared-requant-pair semantics this
        resolves ISA ambiguity #1 with."""
        if (a.height, a.width, a.channels) != (b.height, b.width, b.channels):
            raise ValueError(
                f"add: shape mismatch {a.height,a.width,a.channels} vs {b.height,b.width,b.channels}"
            )
        if requant_scale is None or requant_shift is None:
            eff = a.quant.scale / (output_scale if output_scale is not None else a.quant.scale)
            requant_scale, requant_shift = quantize_scale(eff)
        out_t = Tensor(
            name=name or self._auto_name("add"),
            height=a.height,
            width=a.width,
            channels=a.channels,
            quant=QuantParams(output_scale if output_scale is not None else a.quant.scale),
        )
        op = AddOp(
            name=out_t.name,
            inputs=[a, b],
            output=out_t,
            requant_scale=requant_scale,
            requant_shift=requant_shift,
        )
        out_t.producer = op
        self._register_op(op)
        return out_t

    def upsample2x(self, x: Tensor, *, name: str | None = None) -> Tensor:
        """`OPCODE_UPSAMPLE`, nearest-neighbour 2x2 replicate."""
        out_t = Tensor(
            name=name or self._auto_name("upsample"),
            height=x.height * 2,
            width=x.width * 2,
            channels=x.channels,
            quant=x.quant,
        )
        op = UpsampleOp(name=out_t.name, inputs=[x], output=out_t, factor=2)
        out_t.producer = op
        self._register_op(op)
        return out_t

    def copy(self, x: Tensor, *, name: str | None = None) -> Tensor:
        """`OPCODE_COPY`: local-to-local (or any-space-to-any-space)
        byte copy, shape/quant preserved exactly."""
        out_t = Tensor(
            name=name or self._auto_name("copy"), height=x.height, width=x.width, channels=x.channels, quant=x.quant
        )
        op = CopyOp(name=out_t.name, inputs=[x], output=out_t)
        out_t.producer = op
        self._register_op(op)
        return out_t

    def act(self, x: Tensor, lut: list[int] | None = None, *, name: str | None = None) -> Tensor:
        """`OPCODE_ACT`. `lut[raw_byte] -> int8` for `raw_byte` in
        `0..255` (i.e. indexed by the *unsigned* byte representation of
        the signed input, matching a hardware LUT addressed by the raw
        activation byte); defaults to a ReLU LUT if omitted."""
        if lut is None:
            lut = [max(0, b - 256 if b >= 128 else b) for b in range(256)]
        if len(lut) != 256:
            raise ValueError(f"act: lut must have exactly 256 entries, got {len(lut)}")
        out_t = Tensor(
            name=name or self._auto_name("act"), height=x.height, width=x.width, channels=x.channels, quant=x.quant
        )
        op = ActOp(name=out_t.name, inputs=[x], output=out_t, lut=list(lut))
        out_t.producer = op
        self._register_op(op)
        return out_t


class _Rng:
    """Thin wrapper around `random.Random(seed)` so every random draw
    used by `Model` funnels through one place, named by what it is
    generating (keeps `Model`'s builder methods free of magic-number
    ranges)."""

    def __init__(self, seed: int) -> None:
        import random

        self._r = random.Random(seed)

    def int8_list(self, n: int, low: int = -128, high: int = 127) -> list[int]:
        return [self._r.randint(low, high) for _ in range(n)]

    def bias_list(self, n: int, magnitude: int = 2000) -> list[int]:
        return [self._r.randint(-magnitude, magnitude) for _ in range(n)]

    def scale_table(self, n: int) -> list[tuple[int, int]]:
        return [quantize_scale(self._r.uniform(1e-3, 2.0)) for _ in range(n)]


__all__ = [
    "QuantParams",
    "Tensor",
    "Activation",
    "Op",
    "Conv2dOp",
    "PoolOp",
    "AddOp",
    "UpsampleOp",
    "CopyOp",
    "ActOp",
    "Model",
    "quantize_scale",
]
